= Trio
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

[.ssd-components]
.Matériel
****
* 36 cartes: 1-12 à ♠, ♥ & ♣.
****

Gagnez des trios (un trio est composé de 3 cartes identiques) avant vos adversaires.

* Mode simple :
** Soit 3 trios, n'importe lesquels
** Soit le trio de 7.

* Mode picante :
** Soit 2 trios liés (parmi ses trios gagnés) dont l'addition ou la soustraction donne 7.
+
====
Par exemple, gagner les trios 2 et 5 ou les trios 2 et 9 donne la victoire.
====
* Soit le trio de 7.


== Règle en individuel

=== Préparation

Mélangez et distribuez des cartes face cachée à chacun selon ce tableau.
Puis placez les cartes restantes au centre de la table, face cachée les unes à côté des autres :

[%autowidth, cols="^,^,^"]
|===
| Joueurs | Cartes par joueurs | Cartes sur la table

h| 3 | 9 | 9
h| 4 | 7 | 8
h| 5 | 6 | 6
h| 6 | 5 | 6
|===

* Chacun prend ses cartes en main sans les montrer aux autres et les classe du plus petit numéro au plus grand.
* Choisissez si vous jouez en mode SIMPLE ou PICANTE.
* Le joueur ayant mangé de l'avocat le plus récemment commence.


=== Le jeu

Les joueurs jouent chacun leur tour en sens horaire.
À son tour, un joueur dévoile des numéros un par un, en révélant successivement des cartes : il doit s'arrêter dès que 2 numéros sont différents, sinon il continue jusqu'à avoir dévoilé 3 numéros identiques.

Pour chaque numéro, il peut choisir d'en dévoiler un :

A. *Au centre de la table.* +
Il retourne face visible la carte de son choix au centre de la table. +
OU
B. *De la main d'un joueur, lui inclus.*
Il dévoile le plus petit ou le plus grand numéro d'un joueur : soit de sa propre main, soit en demandant à un adversaire.
La carte concernée est posée face visible sur la table.

Le tour d'un joueur peut se terminer de deux façons :

* Soit le joueur complète ainsi un trio et le gagne définitivement en prenant les 3 cartes face visible devant lui.
* Soit un numéro dévoilé est différent du précédent, alors tous les numéros dévoilés sont remis en place : faces cachées au centre et/ou rendus à leur(s) propriétaire(s).

Dans les deux cas, on passe au tour du joueur suivant.

[IMPORTANT]
====
* *On peut effectuer plusieurs fois exactement la même action*.
Exemple : demander au même adversaire de dévoiler son plus grand numéro, puis à nouveau le plus grand de ses numéros restants.
* Même quand on dévoile un numéro de sa propre main, c'est forcément son plus petit ou son plus grand (JAMAIS un numéro du milieu de sa main).
* Si un joueur n'a plus de cartes en main à son tour, il joue quand même (avec les cartes au centre et celles des adversaires).
====

.tours
====
Hadrien demande à Yanis son plus petit n° (un 3) puis à Martine son plus petit n° (un 2).
Son tour s'arrête alors immédiatement.
Les 2 cartes différentes retournent dans les mains de leurs propriétaires et l'on passe au suivant.

Martine retourne une carte au milieu (un 2), puis dévoile son plus petit n° (un 2) et dévoile à nouveau son plus petit n° (un 2).
Elle gagne donc le trio de 2 et l'on passe au suivant.
====


=== Fin du jeu

Un joueur remporte la partie dès qu'il a gagné :
* 3 trios ou 2 trios liés (dont l'addition ou la soustraction donne 7) selon le mode choisi (SIMPLE ou PICANTE) +
OU
* le trio de 7 (qui donne toujours la victoire) !


== Règles en équipes (à 4 ou 6 joueurs)

Appliquez ces ajustements par rapport à la règle précédente :


=== Préparation

* Formez des équipes de 2 joueurs : 2 équipes à 4 joueurs ou 3 équipes à 6 joueurs.
Asseyez-vous à l'opposé de votre partenaire autour de la table et non côte à côte.
* Mélangez et distribuez face cachée toutes les cartes.
Il n'y en a pas au centre de la table.
* Après avoir trié vos cartes, vous pouvez faire un échange avec votre partenaire.
Toutes les équipes peuvent le faire en même temps.

.Échange
****
Si 2 partenaires souhaitent procéder à l'échange, ils choisissent secrètement une de leurs cartes, se les échangent simultanément face cachée et les rangent secrètement au bon endroit dans leur main.

Les échanges sont les seules façons de communiquer avec son partenaire.
Toute autre forme est interdite (oeillades, coups sous la table, montrer l'endroit où l'on range un échange reçu...).
****


=== Le jeu

* À chaque fois qu'un trio est gagné par une équipe, la ou les équipes adverses peuvent procéder à un nouvel échange.
* Les 2 partenaires mettent en commun les trios gagnés.
Il est conseillé de les regrouper devant l'un des 2 joueurs.

.Tour en équipe
====
Hadrien demande à Jade son plus grand n° (un 10) , puis à sa partenaire Martine son plus grand n° (un 10) et dévoile enfin son plus grand n° (un 10).
L'équipe gagne donc ce trio et les 2 autres équipes peuvent faire un échange.
====


=== Fin du jeu

Une équipe remporte la partie dès qu'elle gagne :

* 3 trios ou 2 trios liés (dont l'addition ou la soustraction donne 7) selon le mode choisi (SIMPLE ou PICANTE) +
OU
* le trio de 7 !
