= Bids
:toc: preamble
:toclevels: 4
:icons: font

A game by Lorenzo Simons.

.Components
****
* 168 bid cards: 1-14 in ♠, ♥, ♣ & ♦.
* 16 points cards: 1-14, “x2” & “-‽” in ★.
* 6 special cards: 2 Monkeys, 1 Wolf, 1 Phoenix, 1 Snake & 1 Butterfly.
****

Each player is dealt ten coloured bid cards.
In every round, players will be bidding in ten turns for the ★ point cards in the middle.
Each ★ point card is worth the same number of points as the number that is written on them.
The other colours do not have any meaning in the basic version.
The player with the most points at the end wins.


== Setup

[%autowidth,cols=">.^h,<"]
|===
| 3 players
a|
* 1-10 of ♠, ♥ & ♣
* 1-10, “x2” & “-!” of ★

| 4 players
a|
* 1-10 of ♠, ♥, ♣ & ♦
* 1-10, “x2” & “-!” of ★

| 5 players
a|
* 1-12 of ♠, ♥, ♣ & ♦
* 1-12, “x2” & “-!” of ★
* 1 Monkey

| 6 players
a|
* 1-14 of ♠, ♥, ♣ & ♦
* 1-14, “x2” & “-!” of ★
* 1 Monkey
|===

Separate all the ★ point cards and shuffle the coloured bid cards into one deck.
In a 3 to 5 player game, take out one random bid card from the deck and remove it from play.
In a 6-player game, all bid cards are used.
Add one random point ★ card to the deck of bid cards (two for 5 players or three for 6 players) and give every player ten cards from the deck.
Put the rest of the point ★ cards in the centre face down.


== Playing the game

At the start of each turn, flip over the top point card.
This is the card that players will be bidding for.

All players must bid one by one in clockwise order exactly one of their ten cards at every turn.
In the first turn of the first round, the player with the longest name (surname as a tiebreaker) starts bidding.
The player with the highest bid wins the turn, takes the point ★ card from the middle and places it in front of them.
The used bid cards are discarded and do not have any further meaning in this round.

In case of a tie between the highest bids, the point card(s) of that turn are “burned” and nobody receives any of the point cards.
Burned point cards are placed at the bottom of the point card pile.

In the next turn the player who placed the highest bid or in case of tie, the last player who burned starts bidding (The Burner is the Turner).


=== ★ in hand

A player can have a point ★ card in his hand that he received when the cards were handed out to the players.
He also needs to bid with this card like any other card, but the value of that ★ card is added to the value of that turn.

.★ bid
====
Players are bidding for a ★5 and one of the players bids a ★8, the winner of the turn receives 8 + 5 points.
If the ★8 is the highest bid (and there is no tie), this player wins the 8 + 5 points.
If the bid of one of the other players is higher, that other player will take both cards and receive 8 + 5 points.
====


=== End of a round

A round ends after ten turns.
This means that not all point cards in the middle will be turned around.
Sum all points with the points of previous rounds and the next round can start.

In the following round, the player with the highest total score starts bidding in the first turn.
In case of a tie, the score in the last round is the tiebreaker.
If this is still the same, the player with the highest card in the last round starts.

The game finishes after six rounds unless all players agree on a different number.


=== The lucky loser

All players who do not have any ★ card in front of them at the end of a round receive a number of points depending on the number of players and how many rounds they have won the lucky loser points.

[%autowidth,cols="^h,^,^,^,^"]
|===
| # rounds | 3 players      | 4 players     | 5 players     | 6 players

| 1        | stem:[1*12=12] | stem:[1*8=12] | stem:[1*8=12] | stem:[1*7=12]
| 2        | stem:[2*12=24] | stem:[2*8=16] | stem:[2*8=16] | stem:[2*7=14]
| 3        | stem:[3*12=36] | stem:[3*8=24] | stem:[3*8=24] | stem:[3*7=21]
| 4        | stem:[4*12=48] | stem:[4*8=32] | stem:[4*8=32] | stem:[4*7=28]
| 5        | stem:[5*12=60] | stem:[5*8=40] | stem:[5*8=40] | stem:[5*7=35]
| 6        | stem:[6*12=72] | stem:[6*8=48] | stem:[6*8=48] | stem:[6*7=42]
| ...      | stem:[...*12]  | stem:[...*8]  | stem:[...*8]  | stem:[...*7]
|===

.4 players
====
A player wins 9 points in round 1.
In the next three rounds he ends without having any ★ card.
In the fifth round, he receives 13 points and in the last round, he did not have any ★ card in front of him at the end.

This means that after six rounds, he will have stem:[9 + (1*8) + (2*8) + (3*8) + 13 + (4*8) = 102] points.
====


== Colour bids

In colour bids the highest card of the colour(s) of which the most cards are played in that turn, wins.

.Colour bids
====
In a turn the following cards are played: ♥4 – ♠5 – ♣9 – ♠7.
In colour bids the ♠7 wins because there are two ♠ cards and only one ♥ and one ♣.
====

The count of the ★ colour always needs to be increased with 1 because the ★ card in the middle is counted.
In the special case that ★ appears the most and the highest ★ card on the table is the one in the middle, the turn is considered as “burned” and the same player as the previous turn has to start again.


== Special cards

Optionally players can add special cards to the pile of ★ point cards.
If any of these special cards (except for the “-!”) is in the hand of one of the players, that player plays this card like any other card but never wins the turn in which he plays this card.


=== The Monkey

This card is always shuffled into the deck of bid cards and therefore always ends up in the hand of one of the players.
This player plays the Monkey card like any other card and will work together with the winner of the turn in which he played the card.
This means that at the end of the round the points of both players will be summed and divided by two (rounding up in case of an odd number).
In case of a tie between the highest bidders, there is no alliance.
Only one of the Monkey cards is used in the game and the second Monkey card is placed next to the player who played the Monkey card.

When a player is in an alliance with another player but does not have any ★ cards at the end of the round, this player does not receive the lucky loser points for this round, but his lucky loser count is increased with 1.

.5 players
====
In round 1, a player ends without any ★ card, he receives 8 points.

In round 2, he is in an alliance with another player, but he does not have any ★ card at the end of the round.
He receives half of the alliance points but does not receive the 16 points for a lucky loser round.

In round 3 he ends again without ★ cards; now he receives 24 points.
====


=== The “-!”

The player winning the turn in which this card appears, will receive -5 points.

If at the end of the round a player only has this card, his result of that round will be -5 points, and he will not receive the lucky loser points.

If this card is in the hand of one of the players, that player will bid -5 when he plays this card and the “-!” will go to the winner of the turn in which this card is played.

If the highest bid is a tie, nobody receives this card.


=== The “×2”

For the player who wins this card, all the points received in the previous turns will be doubled.
This card has no effect on the points received afterwards.
Point cards that are played in the same turn as the “×2” appears are also doubled.

If this card is in the hand of one of the players, he plays this card and the “×2” will go to the winner of the turn in which this card is played.
You can never win this card if it is in your hands.

If the highest bid is a tie, nobody receives this card.


=== The Wolf

The player winning the turn in which this card appears, has to steal one point card from the person who has the lowest bid in that turn.

====
The bids are 10 - 8 - 6 - 5, the player who bid 10 has to steal one of the cards of the player who bid 5.
The player chooses one of the cards that the player with the “5” already won earlier in that round.
====

If the person who has the lowest bid has not won any cards that round, the thief steals from the lowest bidder who already won a card.
If the lowest bid is a tie, the thief can choose from whom he steals.

If the highest bid is a tie, nobody receives this card.


=== The Phoenix

When this card appears, there is no bidding for this card.
The remaining point cards pile is shuffled again and the card is discarded.

This means that all point cards that were burned (see description before) can appear again.
The next point card is turned around and bidding continues.

If this card is in the hand of one of the players, the pile of the ★ cards is shuffled at the end of the turn before turning the next ★ card.
If in this latter case the highest bid is a tie, the pile will not be shuffled.


=== The Snake

When this card appears, there is no bidding for this card.
From this moment on, the lowest bidder will be the winner for the rest of the round.
The card is put aside and the next point card is turned around.

If the card is in the hand of one of the players, the rule of “lowest bidder wins” comes into place starting from the next turn on, as long as the highest bid is not a tie.
If the highest bid is a tie, the rule does not come into place.


=== The Butterfly

When this card appears, players are bidding for the next point card of the pile without knowing what that card will be.

If this card is in the hand of one of the players, the winner receives the next point card and the current point card that players were bidding for is put at the bottom of the pile of point cards.

If the highest bid is a tie, no one receives any card.
