= Rage
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 96 Color cards: 0-15 in ♠, ♥, ♣, ♦, ✿, ★.
* 16 Action cards:
** 2 Monkeys.
** 3 Phoenix.
** 3 Snakes.
** 4 Wolves.
** 4 Butterflies.
****

Each player will be dealt a number of cards for each round.
Each player in turn lays down a card into the middle of the table.
The player who played the highest card of the led color (or the Trump color) wins the trick and takes the cards.
The game ends after ten rounds, and the player who best predicted the number of tricks he would take each turn is the winner.


== Game Setup

A player is chosen as scorekeeper.
He then shuffles the cards and deals 10 to each player.
After each round, the player on the dealer’s left becomes the new dealer.


== Game Play

=== The Deal

In the first round, each player is dealt ten cards.
With each card, a player could win a trick.
Thus, it is possible to win ten tricks in the first round.
In the second round, each player is dealt nine cards.
In this round, it is possible to win up to nine tricks.
In the third round, eight cards are dealt to each player, then seven cards, etc., into the tenth round when each player receives only one card.

The stack of cards that are not dealt out are placed face down in the middle of the table.
The top card is turned over and placed next to the pile.
This card determines the trump color for the current round.
If an Action Card is turned over, turn over another card until a colored card is revealed.


=== Bidding

After the players have sorted their cards by color and value, each player considers how many tricks he will win in this round.
Beginning with the player to the left of the dealer, each player then states their bid for the round.
The scorekeeper notes the bids on the score-sheet.


=== Tricks

The player to the left of the dealer plays the first card in the trick.
Play proceeds in a clockwise direction when each player plays a card.
A card of the lead color *must be played* by each player, if possible.
If a player does not have cards of the lead suit, he may play a card of any color, including trump, or any Action Cards.

If a player does not have the color led for the trick, he may play a card in the trump color (the color of the card next to the trump pile), and thus win the trick.
If several trump cards are in the trick, the highest trump card wins the trick.

.Winning the Trick
****
The player who played the highest card in the color which led the trick wins the trick, unless a card in the trump color is played.
Then the highest card in the trump color wins the trick.
****

Tricks won by a player should be placed in *separate piles*, so it is always known how many tricks each player has won to this point.
The winner of a trick opens the next trick by playing a new card.
When each player has no more cards in their hand, then the round is scored (see, <<scoring>>).


==== Rules for using action cards

If a player does not have a card of the color that was led for the trick, he may play an Action card.
The Action card does not belong to any of the six colors.

* *Phoenix*: The winner of the trick which includes this Action card has *five points added* to their score at the end of this round.

* *Snake*: The winner of the trick which includes this Action card has *five points subtracted* to their score at the end of this round.

* *Wolf*: When this card is played, the trump card is turned face down next to the trump pile.
For this trick, there is no trump.
Any trump cards already played in the trick are counted as normal color cards.
The player who played the highest card of the led color of the trick wins the trick.
+
.Wolf
====
Trump color is ♥. +
Anja begins play and leads with a ♦8. +
Bernd follows with a ♥4 (trump). +
Claudia plays the Wolf Action card : the trump card next to the pile is turned over.
♥ is no longer the trump color. +
Anja receives the trick because she had the highest card in the first played color (♦) in the trick and there is no trump for this trick.
====
+
After the trick, the top card of the face-down pile is flipped over and placed on the card which determined the previous trump.
If an Action Card is turned over, turn over another card until a colored card is revealed.
The new color card determines trump for the duration of the round.

* *Butterfly*: When this card is played by a player, immediately turn over the top card of the trump pile and cover the previous trump card.
If this is an Action card, or a card of the same color as the previous trump, repeat the process until a color card is turned over.
The color of the new card determines the trump color for the current trick as well as the rest of the round.
The previous trump card is no longer valid for this trick or for the rest of the round.
The new trump color can never be the same color as the previous one.

* *Monkey*: When this card is played, the player must announce what color the Monkey will be.
The selected color may be the trump color.
The Monkey is considered the highest card of the selected color in the trick.
If the color selected for the Monkey is not the Trump color, then every card in the Trump color is considered to be a higher value than the Monkey.
If both Monkeys are played in a single trick, then the second Monkey is considered higher than the first.

CAUTION: The first card of a trick may be an Action Card.
The second card played in a trick begun with an Action Card may be any other card.
The first color or Monkey played will determine the suit of the trick.
If only Action Cards, not including Jokers, are played, the first card played in the round wins the trick.


[[scoring]]
== Scoring the round

After all tricks in the round are completed (when the players have no more cards in their hands), the round is scored.
* Each player receives one point for each trick they won.
* Each player receives five points for each *Phoenix* card that were in the tricks they won.
* Each player loses five points for each *Snake* card that were in the tricks they won.
* If a player correctly predicted the number of tricks they won, they receive 10 points.
* If a player failed to correctly predict the number of tricks they won, they lose 5 points.
The total number of points is recorded on the score-sheet.

.First round with ten cards
====
* Anja bid and took three tricks.
She receives ten points, plus three points for the three tricks she took.
Unfortunately, she also received the Snake Action card which means she also loses five points, so she receives eight points (stem:[10 + 3 - 5 = 8]) for this round.
* Bernd did not take the number of tricks he predicted he would (-5 points).
In the trick he took, there was the Phoenix Action card (5 points).
For the single trick he took he gets one point.
Therefore, Bernd gets one point for the round (stem:[-5 + 5 + 1 = 1]).
* Claudia bid and took two tricks (10 points).
She also receives one point for each of the tricks she took.
For this round, she scored twelve points (stem:[10 + 2 = 12]).
* Dieter failed to make his bid (-5 points).
He gets four points for taking tricks.
Therefore, Dieter’s score is a negative one point (stem:[-5 + 4 = -1]) for the round.
====


== Game end

The game ends after ten rounds.
The final round is scored, then the scores of all ten rounds are added up.
The player with the highest score is the winner.


== Variants

* *Plus/Minus One*: As before, the bids are stated openly to the scorekeeper.
The total number of bids may not equal the total number of tricks available.
For example, in a round with five tricks, the total number of bids by all the players cannot equal 5.
The last player to bid is therefore constrained.

* *Hidden Bid*: Every player records their bid on a piece of paper.
When everyone has finished, bids are announced and recorded by the scorekeeper.
This keeps the bids of each player unaffected by their competitor’s bids.

* *Secret Bidding*: Each player writes their bid on a piece of paper.
The bids are disclosed after the last trick is taken.
Therefore, it is unclear during the round how many tricks each player would like to win.

* *Marching Through*: If a player wins all the tricks in a round, he receives two points for each trick taken, instead of only one.
This does not count in the last round where there is only one trick.

* *Reverse Order*: Start with the round of 1 card, and proceed to 10.
Rounds 1 through 3 are pretty much blind luck, anyway.
Get them out of the way, and then play the more skillful round 4 through 10.
This will keep the game closer, by giving players more opportunity to target the leader with Snakes.

* *No Trump Rounds*: When flipping cards to determine trump, if a Butterfly card comes up, immediately begin to play as if there is no trump suit.
Until someone changes trump, of course.
