= Oh 7 ‽
:toc: preamble
:toclevels: 4
:icons: font

A game by Salomon BRYS.

.Components
****
* Base game :
** 5 A cards: ♠, ♥, ♣, ♦, ✿.
** 40 game cards: 0-7 in ♠, ♥, ♣, ♦, ✿.
* Advanced game :
** 4 ★ cards: 1-4.
** 2 Butterfly cards.
** 1 Monkey King card.
****

Oh 7 ‽ plays in several rounds of 7 tricks.
You will bet the number of tricks that you will win, with one of your own cards.
Will you have the necessary card, or will you need to adapt?

To score a maximum of points, you will have to not only take risks, but also try to make your opponent fail their own bets.


== Setup

Create the card game deck by shuffling all game cards of as many colours as there are players:

- 3 players : ♠, ♥, ♣
- 4 players : ♠, ♥, ♣, ♦
- 5 players : ♠, ♥, ♣, ♦, ✿

NOTE: The base game is limited to 5 players, while the <<advanced-game>> allows to up to 6 players.

You should take a pencil and paper to write down bets & scores.


== Round overview

For each round, play the following phases, in order.

1. Distribution
2. Bets
3. Trick taking
4. Scoring

The game usually takes 7 to 9 rounds.


[[distribution]]
=== Distribution

Place the A cards in a face down pile in the centre of the table.

Distribute 7 cards to each player.
Put aside the remaining cards (*the discard*), they won't be used for this round.

TIP: Check that the discard is composed of as many card as there are players.


=== Bets

1. Each player chooses a card for their hand and puts it face down on the table.

2. When everyone has chosen a card, they reveal it.
For each player, the value of their chosen card defines the exact number of tricks that they commit to win during the round (their bet).
+
[IMPORTANT]
====
*The sum of the bets cannot equal 7!* +
If that is the case, restart the Bets phase at stage 1 *leaving the previous bet cards on the table*.
Each player must use *another card* to bet.

Only the last chosen card defines the player's bet.

At the second bet, if the sum of the bets is still 7, all players must bet again with a third card.

If, at the third bet, the sum is still 7, restart the round at the <<distribution>> phase by shuffling all game cards (including the discard).
====

3. Note on a paper sheet the bet of each player.

4. The first leader is the player who bet the *card with the highest value*.
In case of a tie, the player amongst them who bet with the highest priority suit.
+
IMPORTANT: The suit priority is : ♠ > ♥ > ♣ > ♦ > ✿. +

5. The bet card of the first leader defines the *trump suit* for the round.
Take the matching A card, and place face up it on top of the A cards pile.
It reminds all players of the trump suit for the round.

.Bets
====
Alice bets the *♣2*. +
Bob bets the *♠3*. +
Carole bets the *♠2*. +
David bets the *♥0*.

As the sum of the bets is 7, they need to bet again.

Alice bets the *♣3*. +
Bob bets the *♥3*. +
Carole bets the *♥2*. +
David bets the *♠0*.

As Alice and Bob have both bet 3, the suit priority decides.
♥ being higher priority than ♣, Bob becomes the first leader, and his card defines ♥ as the trump suit for the round.
====


=== Trick taking

This phase is played in 7 tricks.
Each player will therefore play their full hand.

The first leader leads the first trick.
Each following trick is lead by the winner of the previous trick.

Each trick plays as such :

1. The leader chooses a card from their hand and plays it face up on the table.
The suit of the card is called *lead suit*.

2. In clockwise order, each other player chooses a card from their hand and plays it face up on the table.
+
IMPORTANT: The suit of this card *must* be of the lead suit if possible.
If you don't have a card of the lead suit, you can play *any* other card.

3. Define the trick winner:
+
* If there are cards of the trump suit in the trick: the player who played *the highest trump suit card* wins the trick.
* If there are no card of the trump suit in the trick: the player who played *the highest lead suit card* wins the trick.
+
That player takes the cards of the trick and places them face down in front of them.
If that wasn't the 7th trick, they become the leader of the next trick.
+
CAUTION: Each player should place the tricks they won next to each other so that *everybody can see the number of trick won by each player*.
         This information is public and always visible.

Once all seven tricks have been played, tally up the scores.


=== Scoring

* Each player who *failed* their bet *looses* as many points as difference between their bet and the number of tricks they won.
+
NOTE: It is totally possible to have a negative score. +
      At the end of the first round, at least one player will have a negative score.

The sum of the points lost by the players who failed their bet during this round makes *the basket*.

* Each player who *made exactly their bet* scores:
** 2 points for making their bet
** + the basket
** + 1 point for each trick they won.

.Scores
====
Following the previous example, after having played the trick-taking phase:

Alice won *3* tricks, making her bet. +
Bob won *4* trick, failing his bet (difference of stem:[1] trick). +
Carole didn't win any trick, failing her bet (difference of stem:[2] tricks). +
David didn't win any trick, making his bet.

The basket is therefore comprised of stem:[1 + 2 = 3] points.

* Players who failed their bet:
** Bob looses stem:[1] point.
** Carole looses stem:[2] points.
* Players who made their bet:
** Alice wins stem:[3 + 2 + 3 = 8] points.
** David wins stem:[3 + 2 + 0 = 5] points.
====

The game is played in a *minimum* of 7 rounds.
However, it is not possible to win the game with a last failure.

Beginning at the end of the 7^th^ round, the player with the highest score wins the game *if they made their bet during the last round*.
If the player with the highest score did not make their bet during the last round, then additional rounds are played until a winner can be designated.

To win the game, a player must therefore :

** have played at least 7 rounds,
** have made their bet during the last round,
** have the highest score.

In case of a tie for the highest score :

* If at least one of the tied players failed their bet, an additional round is played (the leader must be exceeded).
* If all tied players have made their bet, the player who succeeded the most of their bets wins the game. +
  If there is still a tie, the tied players share the victory.
+
NOTE: Players can agree beforehand that all ties trigger an additional round.


[[advanced-game]]
== Advanced game

*For 3 to 6 players.*

Play with one suit less than the number of players:

- 3 players : ♠, ♥
- 4 players : ♠, ♥, ♣
- 5 players : ♠, ♥, ♣, ♦
- 6 players : ♠, ♥, ♣, ♦, ✿

Add the *special cards*:

* *Cards 1 to 4 of suit ★*:
** In the bet phase: +
The player of a ★ card cannot become first leader (even if they played the highest value card).
To define the first leader, cards of suit ★ are ignored.
The suit ★ will therefore never be trump.
** In the trick-taking phase: +
The ★ cards are considered of the lead suit. +
The ★ cards are weaker than lead suit cards of the same value.
(For example, if ♥ is the lead suit, the order is therefore 2♥ > 2★ > 1♥).
* *2 Butterfly cards* :
** In the bet phase: +
A Butterfly card corresponds to a bet of 0 trick.
If the bet is made, the player *does not score* the 2 points for their bet (they therefore only score the basket).
** In the trick-taking phase: +
A butterfly card is lower than any other card: it can never win a trick.
* *1 Monkey King card* :
** In the bet phase: +
The Monkey King card *cannot be used to bet*. +
However, in case of a tie for the highest bet, you can show that you have the Monkey King card in hand to win the tie (instead of using the suit priority order).
** In the trick-taking phase: +
The Monkey King card is stronger than any non-trump card, but weaker than any trump card.

[CAUTION]
====
* Special cards can be played at any time, whether you have cards of the lead suit or not.

* If a player opens with a special card, then the lead suit is defined by the next player.
If they also play a special card, then the lead suit is defined by the next player, and so on. +
If a trick only contains special cards, then the stronger card is the Monkey King, followed by the ★ cards, followed by the Butterfly cards.
====


== 2 Players

Create the card game deck as if you were playing with three players.

Both players will face each other and a third Dummy player will be simulated.

Deal a hand of 7 cards to each player.
Put the remaining cards in a pile between players: that's the *Dummy* pile.

During the bet phase, the Dummy always bets 2.
Therefore, if the sum of the players bets plus 2 is 7, they need to re-bet.
The Dummy never becomes first leader (its bet is ignored for that purpose).

After the bet phase, before starting the first trick, reveal 2 cards from the Dummy pile and place them face up next to it.

The Dummy always plays last (after both players), unless it won the previous trick, in which case it opens the trick, followed by the first leader.

The Dummy tries to win exactly 2 tricks.

Each time the Dummy plays last, reveal a third card from its pile and play one of the three revealed cards on its behalf:

* *If it wants to win the trick* (because it has won fewer than 2 tricks):
** *If it can win the trick*:
*** *If it is its first trick*: it plays the lowest card that wins the trick.
*** *If it is its second trick*: it plays the highest card that wins the trick.
** *If it cannot win the trick*: it plays the lowest possible card.
* *If it wants to lose the trick* (because it has already won 2 tricks):
** *If it can lose the trick*: it plays the highest card that looses the trick.
** *If it cannot lose the trick*: it plays the highest possible card.

In case of a tie for non-trump highest or lowest card, it follows the suit order.

If the Dummy plays first (because it won the previous trick), it plays the first card from its pile (its 2 reveal cards stay on the table).

Do not keep scores for the Dummy.
