= Jekyll vs Hyde
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

Un jeu de Geon-il.

.Matériel
****
* 21 cartes Lutte : 1-7 à ♠, ♥, ♣.
* 4 cartes Étoiles : 2-5 à ★.
* 3 cartes A : ♠, ♥ & ♣.
* 3 cartes Ordre : 1-3 à ♦.
****

Jekyll vs Hyde est un jeu de plis pour 2 joueurs inspiré du roman L'Étrange Cas du docteur Jekyll et de M. Hyde de R.L. Stevenson.
Chaque joueur incarne une facette de la personnalité du personnage principal : le Dr Jekyll cherche à cacher sa double nature sans perdre la raison,
tandis que Mr. Hyde, son alter ego, cherche à le dominer et le faire basculer dans les ténèbres.

L’un des joueurs joue le Dr. Jekyll ; l’autre sera Mr. Hyde.
La partie se joue en trois manches.
À l’issue de chaque manche, la personnalité de Dr. Jekyll s’affaisse sous les assauts de Mr. Hyde.

Mr. Hyde l’emporte s’il parvient à gagner 5 points.
S’il n’a pas réussi à le faire en trois manches, c’est le Dr. Jekyll qui l’emporte, en se libérant de l’influence maléfique de son adversaire.


== Mise en place

1. Déterminez qui sera le Dr. Jekyll et qui sera Mr. Hyde.
2. Donnez à chaque joueur la carte référence correspondant à son rôle.
3. Placez les trois cartes Ordre dans l'ordre (1 à 3) entre les deux joueurs et les trois cartes A face caché à côté.
4. Mélangez les cartes Lutte avec les cartes ★.
5. Dr. Jekyll joue en premier.


== Comment Jouer

La partie se déroule en trois manches. +
À chaque manche, jouez les phases suivantes, dans l’ordre.

1. Préparation
2. Lutte
3. Progression du Mal


=== 1. Préparation

Chaque joueur reçoit 10 cartes (mettez de côté les 5 cartes qui n’ont pas été distribuées).

Chaque joueur choisit une carte de sa main et l’échange avec son adversaire.
L’échange se fait simultanément, face cachée (vous échangerez 2 cartes au début de la 2e manche et 3 cartes au début de la 3e).

CAUTION: Si vous recevez au moins 2 cartes ★ dès le début de la manche, vous devez en inclure au moins 1 dans l’échange.

.Example de la manche 2
====
C’est le début de la 2e manche.
Les joueurs doivent échanger 2 cartes chacun. +

Dr. Jekyll a reçu 3 cartes ★ et doit donc en échanger au moins une.
Mr. Hyde n’en a qu’une seule, et n’est pas obligé de l’échanger.
====


=== 2. Lutte

Le nombre de points de Mr. Hyde au début de la manche détermine qui sera le premier joueur. +
Si Mr Hyde a 0, 1 ou 2 points, c’est le Dr. Jekyll qui commence.
Si Mr Hyde a 3 points ou plus, c'est lui qui commence.
Le Dr. Jekyll commence donc toujours la première manche.


*Une manche se joue en 10 plis, qui se déroulent chacun comme suit :*

- Le premier joueur joue n’importe quelle carte de sa main, face visible.
- Si le premier joueur joue une carte d’une couleur donnée, son adversaire doit jouer une carte de cette couleur.
  Il peut aussi jouer une carte ★ à la place.
  S’il n’a pas la couleur demandée, il peut jouer n’importe quelle carte de sa main.
- Si le premier joueur joue une carte ★, alors il doit annoncer une couleur.
  Son adversaire doit jouer cette couleur *(même s’il a une carte ★ !)*.
  S’il ne peut pas, il peut jouer n’importe quelle carte de sa main.

*On compare ensuite les cartes :*

- Si les deux cartes sont de la même couleur, la carte de plus haute valeur l’emporte.
- Si les deux cartes sont de couleur différente, la couleur la plus forte l’emporte (voir plus loin), et ce quelle que soit sa valeur.
- Si une carte ★ a été jouée, résolvez d’abord son effet ; puis, la carte de plus haute valeur l’emporte.

Le vainqueur du pli ramasse les deux cartes et devient le premier joueur du pli suivant.

.Qu’est-ce qu’un jeu de plis ?
[TIP]
====
À chaque tour d’un jeu de plis, chaque joueur joue une carte sur la table ; traditionnellement, la carte de plus haute valeur l’emporte.
On dit que les cartes jouées forment une levée (historiquement, on levait la main pour les ramasser) ou un pli (on les regroupait en pliant la main).
====

.Ordre des couleurs
****
Les couleurs ne sont pas classées au début de la partie.
C’est en cours de manche que leur rang sera défini.

La première couleur à apparaître (première carte Lutte jouée) acquiert automatiquement le rang le plus faible.
Placez immédiatement la carte A correspondante à l'emplacement appropriée sous la carte Ordre (flèche de gauche).
Lorsque la deuxième couleur apparaît, placez sa carte A à l'emplacement du milieu.
Dès cet instant, la couleur qui n’a pas encore été jouée devient automatiquement la meilleure couleur de la  manche.
Les cartes ★ n’ont pas de couleur et ne peuvent pas être classées.

.Example
====
1. Le Dr. Jekyll joue le 6♠.
   Comme il s’agit de la première carte Lutte de la manche, ♠ prend le rang le plus faible et la carte A♠ est placée sous la carte 1♦.
2. Mr. Hyde n’a pas de ♠ en main.
   Il joue donc le 4♥.
   La carte A♥ est immédiatement placé à l'emplacement sous la carte 2♦, et Mr. Hyde gagne ce pli, car la couleur a priorité sur la valeur et ♥ est mieux classé que ♠.
3. Automatiquement, la carte A♣ est placée sous la carte 3♦.
====
****

.Cartes ★
****
Lorsqu’un joueur joue une carte ★, son effet dépend de la carte jouée par son adversaire :

* ♠ (Bleu) : le vainqueur de ce pli vole un pli (composé de 2 cartes) à son adversaire.
* ♣ (Vert) : les deux joueurs choisissent 2 cartes de leur main (ou 1, si c’est la dernière) et les échangent simultanément.
* ♥ (Rouge) : retirez les cartes A des cartes Ordre et replacez-les à côté face cachée.
  L’ordre des couleurs est réinitialisé : la prochaine carte jouée définira la couleur la plus faible, et ainsi de suite.

[NOTE]
====
* Dans tous les cas, lorsqu’une carte ★ est jouée, c’est toujours la plus haute valeur qui l’emporte.
* Double ★ : si les deux joueurs posent une carte ★, alors elles se neutralisent.
  Il ne se passe rien et la plus haute valeur l’emporte.
====

CAUTION: Les cartes ★ sont plus fortes que les autres cartes de même valeur. +
Par exemple, le 3★ est plus fort que n'importe quel autre 2, mais plus faible que n'importe quel autre 3.

.Example
====
Le Dr. Jekyll joue le 4 d'★ en tant que premier joueur et demande du ♥.
Mr. Hyde joue le 6♥.
L’effet de la carte ★ réinitialise l’ordre des couleurs tandis que Mr. Hyde, qui a joué une carte de meilleure valeur, gagne le pli.
====
****


=== 3. Progression du Mal

Comparez le nombre de plis remporté par chaque joueur durant cette manche, soustrayez le score le plus faible du score le plus élevé et divisez ce résultat par deux
(par exemple si le Dr. Jekyll a gagné 6 plis contre 4, le résultat est de stem:[(6-4)/2 = 1]).
Ce résultat indique de combien de points Mr. Hyde obtiens pour cette manche.

NOTE: Le Mal est inexorable !
      Même si le Dr. Jekyll gagne plus de plis que son adversaire, Mr Hyde obtiens des points.
      Le but du Dr. Jekyll est de maintenir l’équilibre sans céder aux ténèbres !

Si Mr. Hyde a maintenant 5 points ou plus, il remporte instantanément la partie.
Sinon, commencez une nouvelle manche : retirez les 3 cartes A des cartes Ordre et remélangez toutes les cartes (y compris les 5 écartées en début de partie).


== Fin de la partie

Le Dr. Jekyll gagne la partie à l’issue de la 3e et dernière manche si Mr Hyde n'a pas réussi à obtenir 5 points.


== Variante expert

Jouer le Dr. Jekyll est délicat : vous serez constamment sous pression et planifierez soigneusement toute action.
Pour une partie plus  équilibrée et plus tactique, jouez deux parties en alternant les rôles.

Mr. Hyde ne gagne plus la partie avec 5 points.
À la place, il doit obtenir le maximum de points en trois manches.

Après deux parties, le meilleur Mr. Hyde gagne le match.
En cas d'égalité, jouez un nouveau match !
