= Seven Seals
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 75 numbered cards: 1-15 in ♠, ♥, ♣, ♦, ★.
* 27 seals:
** 17 colour seals:
*** 12 for regular colours: 3 Ks in ♠, ♥, ♣, ♦.
*** 5 for the trump colour: 3 Ks, C, & S in ★
+
NOTE: The C & S cards are no different from the K Cards.
(The Super-Set Deck only provides 3 Ks).
** 10 magical seals: 6 Wolves & 4 Butterflies
* The black magician: A in ⎈
****

Back at the magician's academy, the students of magic have to face the new challenge.
Each budding magician has to predict how many tricks he or she will win and which colours they will be.
In order to record the prediction, he or she has to take a certain number of coloured seals which he or she has to get rid of during the game.
There are also seals carrying white or black magic.
And as though prediction wasn't hard enough in itself, there's also an unpredictable black magician constantly trying to interfere with the other apprentices' game.
The apprentice to have earned the fewest penalty points after several rounds wins the game and is appointed a magician first class.


== Preparation

Depending on the number of apprentices playing, shuffle these cards and deal them evenly:

* Three apprentices: cards from 1-9 of each colour
* Four apprentices: cards from 1-12 of each colour
* Five apprentices: all 75 cards

The remaining cards, if any, go back in the box.
Each apprentice gets a 15 cards hand.

The black magician and the 27 seals are placed in the centre of the table.


== Prediction

The apprentice to the left of the dealer makes the first prediction.
Then each of the other apprentices makes one, in a clockwise direction.
The apprentice whose turn it is has to:

* either predict how many trick he or she is going to win and take the corresponding number of seals in the correct colours,
* or take the black magician (⎈A).

*Only one apprentice* can take *the black magician*.
When the black magician is gone, all other apprentices can only predict their tricks.
No one has to take the black magician.
You may also choose not to take any seal, and thus predict 0 tricks.


=== The black magician and the black penalty seals

It's advisable to take the black magician only if you have very few or no cards of one colour.
The apprentice who takes it does not get any seal in this round.
His or her job is to make the other apprentices take penalty seals by spoiling their plans of winning tricks, either by winning the tricks him- or herself or by discarding cards.
Read more in the sections <<battle-for-tricks>> and <<penalty-points>>.

.Predictions
====
* Frank starts predicting his tricks.
He takes one ★ seal, two ♠ ones and a ♣ one.
He is planning to win ★ red, two ♠ and one ♣ trick.
* Sabine also decides to take seals from the pool: two ♥ ones, one ♠ one and three ★ ones.
* Katrin does not predict any trick.
Instead, she takes the black magician (⎈A) and places it in front of herself.
She will now have to act in such a way as to prevent her opponents from discarding their seals or even make them take Wolf seals.
====


=== The Butterfly seals

The Butterfly seals (jokers) only come into play if the seals of another colour have run out.
If an apprentice wants to take a yellow seal, for example, but there are no more yellow seals in the pool, he or she has to take a yellow seal from any one of the other apprentices.
This apprentice immediately gets a Butterfly seal from the pool at the centre of the table.
The Butterfly seals act as jokers during the game.
See also <<battle-for-tricks>> and <<penalty-points>>.

.Butterfly
====
* It's Peter's turn.
He wants to take two ♦ tricks, one ♣ one and one ♠ one.
First, he takes two ♦ seals and one ♣ one from the pool.
As there are no more ♠ seals left in the pool, he takes the ♠ seal he needs from Sabine.
Sabine gets a Butterfly seal instead.
====


[[battle-for-tricks]]
== Battle for Tricks

The apprentice to the dealer's left starts the first trick.
He or she chooses any card from his or her hand and places it in the middle of the table.
The other apprentices each take turns playing a card on the first one.
If they have any card of the same colour, they have to play one of them.
If they don't have any card of the same colour, they can either play a card of any other colour to discard it or win the trick by playing a ★, as ★ are always trump.


=== Who wins the trick, i.e. all the cards in the middle of the table?

The trick goes to the apprentice who has played the highest ★ (trump) card.
If there are no ★ cards in the trick, it goes to the apprentice who has played the highest card of the same colour that began the trick.
Whoever wins the trick takes it and places it in front of him- or herself face down.

Next, he or she has to return a seal of the same colour as the first card in the trick to the pool at the centre of the table.
Then the apprentice who has won the trick begins the next one by playing a card of his or her choosing.

If an apprentice wins a trick, but can't return a seal of the correct colour, he or she has to take a Wolf seal from the pool.
At the end of the game, each Wolf seal equals three penalty points.

IMPORTANT: If the first card in a trick is ★, the apprentice who has won it has to return a ★ seal.
If another colour has been played first, but has been overtrumped with a ★ card, the winner of the trick can choose to return either a ★ seal or a seal of the same colour as the first card.

Butterfly seals are jokers.
They can be put back in the pool for any trick.
The apprentice who has chosen the black magician (⎈A) has no seals to return, so if he or she wins a trick, he or she simply places it aside face down and starts the next trick with the card of his or her choice.
He or she does not receive any penalty seal.

.Three different tricks
====
* Frank goes first.
He plays the ♥2.
The colour of the trick is now ♥.
Sabine plays the ♥11.
Katrin follows suit with the ♥7.
Peter does not have any ♥ card, so he plays his ♣12 in order to get rid of it.
Sabine's ♥11 wins the trick, so she returns one of her ♥ seals.
* Now it's Sabine's turn to begin the next trick.
She plays the ♦4.
Katrin follows suit with the ♦2, Peter plays the ♦9 and Frank is forced to play his only ♦ card, the 10.
Frank takes the trick.
As he doesn't have a ♦ seal, he has to take a Wolf penalty seal from the pool.
* Frank again starts the trick, playing the ♥8.
Sabine does not have any ♥ card left, so she overtrumps it with a ★3.
Katrin plays a ♥1.
Peter still has no ♥ cards, so he discards his ♣8.
Sabine wins the trick, because she has played a ★ trump card.
She can now return either a ★ or a ♥ seal.
====


[[penalty-points]]
== Allocation of Penalty Points

The round is over as soon as the apprentices have played all of their cards.

* If an apprentice has no more seals left, he or she gets 0 penalty points.
* Each coloured seal still left with an apprentice is worth two penalty points.
* Each Wolf seal counts as three penalty points.
* Each Butterfly seal gives the player who holds it four penalty points.
* The apprentice who has chosen the black magician (⎈A) gets a maximum of four penalty points.
However, for each Wolf seal the other apprentices had to take, one point is deducted from these four.
For example, if the other apprentices had to take three penalty Wolf seals altogether, the black magician gets only one penalty point (stem:[4 – 3 = 1]).
If the black magician has so successfully interfered with the other apprentices' game that they had to take four or more Wolf seals, the black magician does not get any penalty point.

.Scoring
====
* Frank gets three penalty points for his Wolf seal.
* Sabine gets four penalty points for the Butterfly seal.
* Katrin, the black magician, gets two penalty points, because the other apprentices have taken a total of two Wolf seals (stem:[4 – 2 = 2]).
* Peter gets five penalty points: two for the ♦ seal and three for the Wolf seal.
====

The points are written down.
All seals and the black magician are returned to the centre of the table.
The next player in a clockwise direction shuffles the cards and deals each of the apprentices 15.
The player to the dealer's left starts the next round.


== The End

Play as many rounds as there are apprentices playing.

If there are only three apprentices, play six rounds.

The player with the fewest penalty points wins the game.


== Hints and Strategies

* An apprentice winning a trick has to return a seal of the corresponding colour immediately.
Returning it later is not allowed.
* There are only six Wolf seals in every round.
The apprentice who would have to take the seventh seal lucked out, he or she does not have to take one.
* When predicting tricks, all apprentices should keep in mind that trumps (★) can win tricks of any colour, so the apprentice can return a red seal or a seal of the colour the trick has been started in.
* You should take the black magician if you have no or very few cards of at least one colour.
If you don't have to follow suit so often, you have many more chances of interfering with the other apprentices' game by winning tricks and discarding cards.
* If there are three apprentices playing, the black magician is very much in demand, as it's very lucrative.
If you want to make it a little harder to take the black magician, you can choose beforehand to make it worth five penalty points instead of four.
* For a longer game, you can of course decide to play eight rounds with four people or ten rounds with five people.
The game designer recommends that in this case, you raise the prize of the black magician from four to five penalty points after the first half of the rounds.
