= Sept Sceaux
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

A game by  Katja Stremmel.

.Matériel
****
* 75 cartes numérotées : 1-15 à ♠, ♥, ♣, ♦, ★.
* 27 sceaux :
** 17 sceaux de couleur :
*** 12 pour les couleurs classiques : 3 K à ♠, ♥, ♣, ♦.
*** 5 pour la couleur d'atout : 3 K, C & S à ★
+
NOTE: Les cartes C & S ne diffèrent pas des cartes K.
(Le Super-Set Deck ne fournis que 3 K).
** 10 sceaux magiques : 6 Loups & 4 Papillons
* Le Mage Noir : A à ⎈

WARNING: La cartes référence est titrée du nom anglais du jeu : *"Seven Seals"*.
****

Qui aura le plus grand pouvoir divinatoire ?
Les joueurs doivent prédire le nombre de plis qu’ils pensent gagner et dans quelle couleur.
Ils matérialisent leur prédiction en prenant des sceaux colorés dont ils devront se débarrasser au cours du jeu.
Chacun doit annoncer la quantité et la couleur des plis qu’il pense gagner.
Il matérialise sa prédiction en prenant la quantité correspondante de sceaux colorés.
En plus des sceaux colorés, il y a des sceaux magiques Loups & Papillons.
Pour pimenter le tout, il y a enfin l’imprévisible Mage Noir, qui a pour unique tâche de perturber la stratégie des autres.
Après plusieurs manches, celui qui a perdu le moins de points l’emporte et devient Maître des 7 Sceaux.


== Préparation

En fonction du nombre de joueurs, on mélange puis on distribue :

* À 3 joueurs : les cartes de 1 à 9 de chaque couleur
* À 4 joueurs : les cartes de 1 à 12 de chaque couleur
* À 5 joueurs : les 75 cartes

Les cartes qui ne sont pas utilisées sont remisées dans la boîte pour toute la durée de la partie.
Chaque joueur reçoit 15 cartes et les prend en main.

Le Mage Noir et les 27 sceaux sont placés au centre de la table.


== La prédiction

Le joueur placé à gauche du donneur commence par une première prédiction, puis les autres joueurs font de même, dans le sens horaire.
À son tour on doit :

* soit prédire le nombre de plis que l’on pense ramasser dans chaque couleur et prendre la quantité correspondante de sceaux des couleurs respectives.
On peut ne prendre aucun sceau et prédire ainsi que l’on ne récoltera aucun pli.
* soit prendre le Mage Noir (A⎈) ; personne n’est obligé de le prendre, mais il ne peut être pris que par 1 seul joueur.
S’il a déjà été pris, les joueurs suivants peuvent uniquement faire une prédiction de nombre de plis.


=== Le Mage Noir et les Sceaux de pénalité Loups

Celui qui prend le Mage Noir ne reçoit aucun sceau pour la manche et, en prenant des plis ou en évitant d’en prendre, il va tenter de contrecarrer les prédictions des autres pour qu’ils reçoivent des sceaux de pénalité (voir plus loin aux sections <<bataille-pour-plis>> et <<points-de-penalite>>).

.Prédictions
====
* François commence et prend au centre de la table un sceau ★, deux ♠ et un ♣.
Il veut donc faire un pli ★, deux ♠ et un ♣.
* Sabine prend également des sceaux du centre de la table : deux sceaux ♥, un ♠ et trois ★.
* Catherine ne fait aucune prédiction de pli, prend par contre le Mage Noir (A⎈) et le place devant elle.
Sa mission est maintenant claire, lors de cette manche elle va agir pour que les autres ne puissent pas se débarrasser de leurs sceaux ou bien qu’ils soient contraints de prendre des sceaux Loups.
====


=== Les sceaux Papillons

Les sceaux Papillons sont des jokers qui n’entrent en jeu que s’il n’y a plus aucun sceau disponible dans une couleur déterminée.
Si par exemple, un joueur souhaite prendre un sceau ♦ et qu’il n’y en a plus, il doit prendre un sceau ♦ à n’importe lequel de ses adversaires.
Ce dernier reçoit immédiatement un sceau Papillon à titre de compensation.
On peut utiliser ces sceaux Papillons comme joker durant la manche (voir aussi les sections <<bataille-pour-plis>> et <<points-de-penalite>>).

.Papillon
====
* C’est le tour de Pierre. Il veut faire deux plis ♦, un ♣ et un ♠.
Il prend deux sceaux ♦ et un sceau ♣ du centre de la table.
Comme il n’y a plus de sceau ♠ disponible, il prend le sceau ♠ de Sabine.
Sabine reçoit alors un sceau Papillon en dédommagement.
====


[[bataille-pour-plis]]
== Bataille pour les plis

Le joueur à gauche du donneur pose la carte de son choix face visible au centre de la table puis, à tour de rôle dans le sens horaire, chacun doit jouer une carte face visible en suivant s’il le peut dans la couleur demandée.
Celui qui ne peut pas fournir de carte dans la couleur demandée peut couper avec un ★ (un atout) ou se défausser de n’importe quelle carte dans n’importe quelle autre couleur.


=== Qui remporte le pli et donc les cartes qui se trouvent au centre de la table ?

Le joueur qui a joué la carte d’atout (★) la plus forte reçoit le pli.
S’il n’y a pas d’atout dans le pli, le joueur qui remporte le pli est celui qui a joué la carte la plus forte dans la couleur demandée initialement.
Le gagnant prend toutes les cartes du pli et les place, faces cachées, devant lui.

Il doit ensuite remettre au centre de la table un de ses sceaux de la couleur du pli gagné.
S’il n’a pas de sceau de la couleur correspondante, il doit prendre un sceau Loup au centre de la table.
Chaque sceau Loup compte pour trois points de pénalité à la fin de la manche.

Ce même joueur entame ensuite le pli suivant avec la carte de son choix.

IMPORTANT: Si la couleur ★ est jouée comme première carte d’un pli, le gagnant doit rendre un sceau ★.
Si une autre couleur est jouée en premier et le pli remporté avec une carte ★, le gagnant du pli peut rendre au choix soit un sceau de couleur ★, soit un sceau de la couleur demandée au départ.

Les sceaux Papillons sont des jokers et peuvent être rendus pour n’importe quel pli remporté.
Puisque le joueur ayant choisi le Mage Noir ne possède aucun sceau, il met simplement de côté les plis gagnés (il ne reçoit aucun sceau de pénalité) et ouvre le pli suivant avec la carte de son choix.

.Trois différents plis
====
* François ouvre et joue un 2♥ (les joueurs suivants doivent, s’ils le peuvent, jouer une carte ♥).
Sabine suit avec le 11♥.
Catherine suit avec le 7♥.
Pierre n’a pas de ♥ et joue le 12♣.
Sabine gagne le pli avec le 11♥ et remet un de ses sceaux ♥ au centre de la table.
* Sabine ouvre le pli suivant et joue un 4♦.
Catherine suit avec le 2♦, Pierre avec le 9♦ et François avec le 10♦.
François remporte le pli, mais il n’a pas de sceau ♦.
Il doit prendre du centre de la table un sceau de pénalité Loup.
* François ouvre le pli suivant et joue le 8♥.
Sabine n’a pas de ♥ et coupe avec le 3★.
Catherine suit avec le 1♥.
Pierre n’a pas de ♥ et joue un 8♣.
Sabine remporte le pli, car elle a coupé avec le 3★.
Elle peut rendre un sceau ♥ ou un ★.
====


[[points-de-penalite]]
== Distribution des points de pénalité

La manche se termine une fois que toutes les cartes en main ont été jouées, les joueurs comptent alors leurs points de pénalité :

* Les joueurs qui n’ont plus aucun sceau devant eux ne marquent aucun point.
* Chaque sceau de couleur restant aux joueurs compte pour deux points de pénalité.
* Chaque sceau Loup compte pour trois points de pénalité.
* Chaque sceau Papillon compte pour quatre points de pénalité.
* Le joueur ayant choisi de jouer le Mage Noir reçoit quatre points de pénalité au maximum.
Ces quatre points de pénalité sont réduits d’un point pour chaque sceau Loup pris par un joueur adverse.
Si par exemple, les autres joueurs ont dû prendre au total trois sceaux Loups, alors le Mage Noir reçoit : stem:[4 - 3 = 1] point de pénalité.
S’il parvient à mieux perturber le jeu de ses adversaires de manière à ce qu’ils doivent prendre au moins quatre sceaux Loup, le Mage Noir ne marque pas de points de pénalité.

.Points
====
* François reçoit trois points de pénalité pour le sceau Loup.
* Sabine reçoit quatre points de pénalité pour le sceau Papillon.
* Pierre reçoit cinq points de pénalité, deux pour le sceau ♦ et trois pour le sceau Loup.
* Catherine, en tant que Mage Noir, reçoit deux points de pénalité, car les autres ont pris deux sceaux Loups (stem:[4 - 2 = 2]).
====

Les scores sont notés et additionnés aux scores précédents, puis tous les sceaux et le Mage Noir retournent au centre de la table.
Le joueur placé à gauche du précédent donneur redistribue les cartes et celui qui est à sa gauche commence une nouvelle manche.


== Fin de la partie

On joue autant de manches que de joueurs, sauf lors d’une partie à trois joueurs où on jouera six manches.

Celui qui a perdu le moins de points en fin de partie est déclaré vainqueur


== Remarques et conseils tactiques

* Quand on réalise un pli, il faut rendre immédiatement un sceau : il est interdit de le rendre plus tard.
* Il n’y a que 6 sceaux Loups et on ne peut donc pas en distribuer plus de six lors d’une manche.
Le joueur qui devrait prendre un septième sceau Loup a de la chance : il n’en reçoit pas !
* Lors de la prédiction des plis, chaque joueur doit bien penser qu’avec l’atout (cartes ★) chacune des autres couleurs demandées peut être coupée et qu’il peut rendre ainsi un sceau ★ ou le sceau de la couleur appelée.
* Il peut être intéressant de prendre le Mage Noir si on ne possède que peu voir aucune carte dans une ou plusieurs couleurs.
À chaque fois que l’on ne pourra pas suivre, on pourra alors perturber les plans adverses, soit en coupant pour faire le pli, soit en se défaussant d’une forte carte dans une autre couleur.
* Lors d’une partie à trois, le Mage Noir est beaucoup plus attractif et lucratif.
Pour le rendre moins avantageux, les joueurs peuvent convenir en début de partie de fixer à cinq points de pénalité sa valeur nominale.
* Ceux qui souhaitent jouer plus longtemps peuvent convenir de jouer 8 manches à quatre joueurs, ou 10 manches à cinq.
En ce cas, il est recommandé d’augmenter les points de pénalité du Mage Noir dans la seconde moitié de la partie, en les faisant passer de quatre à cinq points de pénalité après la première moitié des manches.
