= Regicide
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 36 numbered cards: 2-10 in ♠, ♥, ♣ & ♦.
* 4 animal companions: A in ♠, ♥, ♣ & ♦.
* 2 butterflies
* 12 enemy cards: J, Q & K in ♠, ♥, ♣ & ♦.
****

A sinister corruption has spread throughout the four great kingdoms, blackening the hearts of once-loved Kings and Queens and those that protect them.
As brave adventurers you must work together using the special powers of your champions and animal companions.
Overthrow the corrupted monarchs, purge them of their darkness and add them to your ranks so that life can be brought to the land once more.


== Aim of the game

Regicide is a cooperative game where players work together to defeat 12 powerful enemies.
Players take turns to play cards to the table to attack the enemy and once enough damage is dealt, the enemy is defeated.
The players win when the last Koala is defeated.
But beware! Each turn the enemy strikes back.
Players will discard cards to satisfy the damage and if they can’t discard enough, everyone loses!


== Setup

Shuffle the 4 **K**oalas and put them face-down in a pile on the table. +
Shuffle the 4 **Q**uetzals and put them face-down on top of the Koalas. +
Shuffle the 4 **J**ellyfishes and put them face-down on top of the Quetzal. +
This is the Castle deck.
Place the Castle deck in the centre of the table and turn the top card face up to reveal a Jellyfish.
This will become the current enemy.

Shuffle together all the cards numbered 2 to 10 with the 4 **A**nimal Companions and a number of Butterfly based on the number of players (see table below) to form your Tavern deck.
The Tavern deck is where cards are dealt and drawn from.

During the game place any discarded cards into a shared discard pile beside the Tavern deck.

Deal cards to each player up to their maximum hand size.

[%autowidth, cols="^, ^, ^"]
|===
| Players | Butterflies | Max. Hand Size

| 1 | 0 | 8
| 2 | 0 | 7
| 3 | 1 | 6
| 4 | 2 | 5
|===

The player to have most recently committed regicide goes first.


== How to play

On their turn a player will play cards from their hand to deal damage to the current enemy in order to defeat it.
The values on the cards determine damage, while the suit provides a special power.

Each turn has four steps:

1. Play a card or yield
2. Activate the suit power
3. Deal damage to the enemy and check
4. Suffer damage from the enemy


=== Step 1 – Play a card from hand to attack the enemy

Play a card from your hand onto the table in front of you.
The number of the card determines the attack value.
So if a 7 of ♥ is played, the attack value is 7.
Instead of playing a card a player may choose to yield (see Yielding).


=== Step 2 – Activate the played card’s suit power

Playing a card to damage the enemy also grants a power associated with the suit of that card.
Powers from red suits are resolved straight away, powers from black suits take effect in later steps.


==== ♥ Hearts

Heal from the discard: Shuffle the discard pile then count out a number of cards face-down equal to the attack value played.
Place them under the Tavern deck (no peeking!) then, return the discard pile to the table, face-up.


==== ♦ Diamonds

Draw cards: The current player draws a card.
The other players follow in clockwise order drawing one card at a time until a number of cards equal to the attack value played have been drawn.
Players that have reached their maximum hand size are skipped.
Players may never draw cards over their maximum hand size.
There is no penalty for failing to draw cards from an empty Tavern deck.


==== ♣ Clubs

Double damage: During Step 3, damage dealt by ♣ counts for double. E.g., the 8 of ♣ deals 16 damage.


==== ♠ Spades

Shield against enemy attack: During Step 4, reduce the attack value of the current enemy by the attack value played.
The shield effects of ♠ are cumulative for all ♠ played against this enemy by any player, and remain in effect until the enemy is defeated.


=== Step 3 – Deal damage and check to see if the enemy is defeated

[%autowidth, cols="^, ^, ^"]
|===
| Enemy | Attack | Health

| **J**ellyfish | 10 | 20
| **Q**uetzal | 15 | 30
| **K**oala | 20 | 40
|===

Damage equal to the attack value of the played card is now dealt to the enemy.
Check to see if the total damage dealt by all players so far is equal to or greater than the enemy’s health.
For example if facing a **J**ellyfish and one player deals 9 damage in their turn, then another player deals 12 damage in their turn, the total damage currently dealt would be 21 so the enemy would be defeated.

If the enemy is defeated, do the following:

[upperroman]
. Place the enemy in the discard pile.
If the players have dealt damage exactly equal to the enemy’s health, place it face-down on top of the Tavern deck instead.
. Place all cards played by players against the enemy in the discard pile.
. Turn the next card of the Castle deck face up.
. The player who has just defeated the enemy skips Step 4 and begins a new turn against the enemy just revealed, starting at Step 1.


=== Step 4 – Suffer damage from the enemy by discarding cards

If not defeated, the enemy attacks the current player by dealing damage equal to that enemy’s attack value.
Remember to reduce the enemy’s attack value by the total value of ♠ that players have played against the enemy.

The current player must discard cards from their hand with a total value at least equal to the enemy’s attack value.
Discard the cards one at a time, face-up to the discard pile.
Animal Companions (*A*) have a value of 1 and the Butterflies a value of 0 when discarded to cover damage.
If the player cannot discard enough cards to satisfy the damage, they die and all players lose the game.
It’s ok to have an empty hand.

After suffering damage, the next player in clockwise order begins their turn, starting at Step 1.


== Animal Companions

In Step 1, Animal Companions (*A*) can be played on their own, but may also be paired with one other card (except the Butterfly).
Animal Companions count as 1 towards the attack total and their suit power is also applied.
For example, when playing the 8 of ♦ with the Animal Companion of ♣ the attack value is 9 and the effects of both suit powers are applied for 9:
9 cards are drawn and 18 damage is dealt.
Any time when both a ♥ power and ♦ power are resolved together, resolve the ♥ healing before drawing with ♦.
Animal Companions can also be paired with one other Animal Companion.
If you play an Animal Companion with another card of the same suit, you only apply the suit power once.


== Combos

In Step 1, instead of playing a single card, players can combine cards together in sets of 2, 3 or 4 of the same number as long as the combined total of the cards played equals 10 or less.
Animal Companions cannot be added to a combo or played as a combo on their own; they can only ever be paired with one other card (which could be another Animal Companion).
So players can play a pair of 2s, 3s, 4s, or 5s, triple 2s and 3s, or quadruple 2s.
When these cards are played together all suit powers are resolved at the total attack value.
For example, if a player plays the 3 of ♦, ♠ and ♣ together, players will draw 9 cards, reduce the enemy’s attack value by 9 and deal 18 damage.
Any time when both a ♥ power and ♦ power are resolved together, resolve the ♥ healing before drawing with ♦.


== Enemy immunity

Each enemy is immune to the suit powers of cards played against them which match their suit.
For example, players will not draw cards when a ♦ is played against the Jellyfish of ♦ (however the number is still added to the damage total).

The Butterfly can be played to cancel an enemy’s immunity.


== Playing the Butterfly

In Step 1 when playing a card the Butterfly may be played (always on its own).
The Butterfly has an attack value of 0.
The power of the Butterfly is that it negates the immunity of the enemy meaning the suit powers of cards with the same suit as the enemy will now take effect when played.
After playing the Butterfly, skip steps 3 and 4 then, instead of play moving to the next player the player of the Butterfly chooses any player to go next.

After playing the Butterfly the normal restrictions on player communication (see <<Communication>>) are temporarily changed.
Until the next player starts their turn players may express their desire (or reluctance) to go next in a general way.
For example, you may say “I have a good play” or “I would rather not go next”.
You still may not reveal the contents of your hand.

If the Butterfly is played against a ♠ enemy, ♠ cards played prior to the Butterfly will begin reducing the attack value of the enemy however ♣ played prior to the Butterfly against a ♣ enemy will not count for double.


== Drawing a defeated enemy

Jellyfishes in hand count as a 10, Quetzal in hand count as a 15 and Koalas in hand count as a 20.
These values are applied when either playing them as an attack card or discarding them from hand to suffer damage.
Their suit power is applied as normal when played.


== Yielding

During Step 1 it may be beneficial to yield instead of playing a card.
To yield simply say “Yield” and move directly to Step 4 (Suffer damage from the enemy), skipping Steps 2 and 3.
A player may not yield if every other player has yielded on their last turn.
For example, in a three player game, if two players have yielded in a row the third player may not yield.


== Communication

Players may not communicate to the other players any information which may reveal or suggest the contents of their hand.
They may however remind other players of any public information such as how many cards they have in their hand.
Some examples of allowed communication are: “I have two cards in hand” or “We only have 3 cards left in the Tavern deck!”.
Some examples of prohibited communication are: “I’ve got a 10 of clubs” or “I hope someone plays a Diamond soon!” or “If you play a Heart then I can probably help us get some cards in hand” or “Don’t kill that enemy, leave them for me!”.

After a Butterfly is played the normal restrictions on player communication are temporarily changed.
Until the next player starts their turn players may express their desire (or reluctance) to go next in a general way.
For example, you may say “I have a good play” or “I would rather not go next”.
You may still not reveal the contents of your hand.


== Game end

The game ends when the players win by defeating the last Koala or when the players lose because a player is unable to satisfy the damage dealt by an enemy.
The players also lose if any player is unable to play a card or yield on their turn.


== Solo play

When playing with only 1 player note the following rule changes:

Set up the game as per usual but place the two Butterflies to the side.
You play with a single hand limited to 8 cards.
Play as normal, playing each turn one after the other.
A Butterfly can be flipped to activate the following power: “Discard your hand and refill to 8 cards - this does not count as drawing for the purpose of enemy ♦ immunity.”
Since you have two Butterflies this can be done twice per game.
Flipping the Butterfly in this way does not cancel enemy immunity.
You are allowed to use the Butterfly power a) at the start of Step 1 before you play a card or b) at the start of Step 4 before you have to take damage.

* A win having used 2 Butterflies = Bronze Victory
* A win having used 1 Butterfly = Silver Victory
* A win having used no Butterfly = Gold Victory
