= Dou Dizhu
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 52 numbered cards: 2-10, J, Q, K, A in ♠, ♥, ♣ & ♦.
* 2 jokers:
** The *Phoenix*.
** The *Dragon*.
****


Dou Dizhu (literally "Fight the Landlord") is a climbing game for three players.
In each hand one player, the "landlord", plays alone and the others form a team.
The landlord's aim is to be the first to play out all his cards in valid combinations, and the team wins if any one of them manages to play all their cards before the landlord.

The game is said to have originated in Hubei province but is now popular all over China.


== Players, Cards and Deal

The cards rank from high to low: +
*Dragon, Phoenix, 2, A, K, Q, J, 10, 9, 8, 7, 6, 5, 4, 3.* +
Suits are irrelevant.

As in most Chinese games the cards are not really dealt, but taken from the deck by the players.

One of the players shuffles the cards, gives them to the player to his left to cut, and stacks them face down in the middle of the playing surface.
One card is turned face up and inserted somewhere near the middle of the stack - this will determine who starts the auction.
The dealer then draws the top card from the deck, looking at it but not showing it to the other players.
The player to dealer's right does the same, then the third player (the dealer) and so on counter-clockwise around the table until each player has 17 cards.
The last three cards are left face down on the table until after the auction.
It saves time if you look at your cards and sort them as you pick them up.


== Auction

There is an auction to determine which player will be the landlord, and play alone against the other two.
The possible bids are 1, 2 and 3.
The player who drew the face up card in the "deal" is the first to bid.
Each player in turn may either pass or bid higher than the highest bid so far.
If everyone passes the hand is thrown in and there is a new deal.
If there is a bid, the bidding continues counter-clockwise, each player passing or bidding higher than the previous bidder, until two consecutive players pass or someone bids 3, which ends the auction since it is the highest possible bid.
The final and highest bidder is the landlord.

The landlord reveals the three face-down cards in the middle for all to see before adding them to their hand for a total of 20 cards.


== Play

The landlord plays first, and may play a single card or any legal combination.
Each subsequent player in anticlockwise order must either pass (play no card) or beat the previous play by playing a higher combination of the *same number of cards* and *same type*.
There are just two exceptions to this: a *rocket* can beat any combination, and a *bomb* can beat any combination except a higher bomb or rocket - see definitions below.
The play continues around the table for as many circuits as necessary until two consecutive players pass.
The played cards are then turned face down and put aside, and the person who played the last card(s) begins again, leading any card or legal combination.

In this game, there are thirteen types of combination that can be played:

. *Single card:* +
  Ranking from three (low) up to Dragon (high) as explained above.

. *Pair:* +
  Two cards of the same rank, from three (low) up to two (high).

. *Triplet:* +
  Three cards of the same rank, from three (low) up to two (high).

. *Triplet with an attached card:* +
  A triplet with any single card added, for example 6-6-6-8.
  These rank according to the rank of the triplet - so for example 9-9-9-3 beats 8-8-8-A.

. *Triplet with an attached pair:* +
  A triplet with a pair added, like a full house in poker, the ranking being determined by the rank of the triplet - for example Q-Q-Q-6-6 beats 10-10-10-K-K.

. *Sequence:* +
  At least five cards of consecutive rank, from 3 up to ace - for example 8-9-10-J-Q.
  Twos and jokers cannot be used.

. *Sequence of pairs:* +
  At least three pairs of consecutive ranks, from 3 up to ace.
  Twos and jokers cannot be used.
  For example 10-10-J-J-Q-Q-K-K.

. *Sequence of triplets:* +
  At least two triplets of consecutive ranks from three up to ace.
  Twos and jokers cannot be used.
  For example 4-4-4-5-5-5.

. *Sequence of triplets with attached cards:*
  An extra card is added to each triplet.
  For example 7-7-7-8-8-8-3-6.
  The attached cards must be different from all the triplets and from each other.
  Although triplets of twos cannot be included, a two or a joker or one of each can be attached, but not both jokers.

. *Sequence of triplets with attached pairs:*
  An extra pair is attached to each triplet.
  Only the triplets have to be in sequence - for example 8-8-8-9-9-9-4-4-J-J.
  The pairs must be different in rank from each other and from all the triplets.
  Although triplets of twos cannot be included, twos can be attached.
  Note that attached single cards and attached pairs cannot be mixed - for example 3-3-3-4-4-4-6-7-7 is not valid.

. *Bomb - four cards of the same rank:* +
  A bomb can beat everything except a rocket, and a higher ranked bomb can beat a lower ranked one.

. *Rocket - the pair of jokers:* +
  It is the highest combination and beats everything else, including bombs.

. *Quadplex set:* +
  There are two types:
+
--
.. A quad with two single cards of different ranks attached, such as 6-6-6-6-8-9.
.. A quad with two pairs of different ranks attached, such as J-J-J-J-9-9-Q-Q.
--
+
Twos and jokers can be attached, but you cannot use both jokers in one quadplex set.
Quadplex sets are ranked according to the rank of the quad.
Note that a quadplex set can only beat a lower quadplex set of the same type, and cannot beat any other type of combination.
+
CAUTION: *A quadplex set is not a bomb*, and can therefore be beaten by a bomb made of lower ranked cards.

Note that passing does not prevent you from playing on a future turn.

.Turn
====
Player A (the landlord) leads 3-3-3-9 to get rid of some low cards.
Player B passes.
Player C plays 5-5-5-7, player A plays K-K-K-J and player B plays A-A-A-3.
C and A pass, so B can start again with anything.
He leads a single 4.

NOTE: B could have played his aces on his the first turn, but preferred to pass to give his partner a chance to get rid of some cards.
After B has passed, C should play if possible, so as not to give the landlord (A) a free chance to lead again.
Having beaten A's second play, B leads a low card to give C the choice of playing another unwanted card or putting the landlord under pressure by playing a high card.
====


== Scoring

If the landlord runs out of cards first he has won, and each opponent pays him the amount of the bid - 1, 2 or 3 points - provided that no bomb or rocket was played.
If one of the other two players runs out before the landlord, the landlord loses and must pay the amount of the bid *to each opponent*.

For each occasion when any player played a bomb or rocket, the payment for the hand is doubled.
So for example in a hand in which two bombs and a rocket were played, a player who bid 3 will win 24 points from each opponent for going out first, or pay 24 to each opponent if another player goes out first.

NOTE: Since the opponents of the landlord stand to win or lose equally, they form a temporary partnership.
When playing against the landlord it is just as profitable to help your partner to run out of cards first as to win yourself.
Because of this the partners will usually not beat each other’s cards, and the weaker partner will play to help the stronger partner.

A pre-determined number of games can be played to determine the overall winner.