= Dou Dizhu
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

[.ssd-components]
.Matériel
****
* 52 cartes numérotées : 2-10, J, Q, K, A à ♠, ♥, ♣ & ♦.
* 2 jokers :
** Le *Phénix*.
** Le *Dragon*.
****


Dou Dizhu (littéralement "Combattre le patron") est un jeu de montée pour trois joueurs.
À chaque manche, le "patron" joue seul et les deux autres forment une équipe.
L'objectif du patron est d'être le premier à avoir joué toutes ses cartes en combinaisons valides, tandis que l'équipe l'emporte si l'un des deux réussis à avoir joué toutes ses cartes avant le Patron.

Le jeu aurait émergé dans la province de l'Hubei et est maintenant populaire dans toute la Chine.


== Joueurs, Cartes et Distribution

L'ordre des cartes, de la plus élevée à la plus basse : +
*Dragon, Phénix, 2, A, K, Q, J, 10, 9, 8, 7, 6, 5, 4, 3.* +
Les couleurs n'ont pas d'importance.

Comme dans la plupart des jeux chinois, les cartes ne sont pas distribuées, mais prises de la pile de carte par les joueurs.

Un des joueurs mélange les cartes et donnes le paquet au joueur à sa gauche pour qu'il le coupe et le place face cachée au centre de la table.
Une carte est retournée face visible et insérée approximativement au milieu du paquet - elle déterminera le joueur qui démarrera les enchères.
Le joueur qui a coupé pioche alors une carte du paquet et la regarde, mais la garde secrète.
Le joueur à sa gauche fait ensuite de même, puis le troisième (celui qui a distribué) et ainsi de suite en sens anti-horaire autour de la table jusqu'à ce que chaque joueur ait 17 cartes.
Les trois dernières cartes sont laissées face cachées sur la table jusqu'à la fin des enchères.
Il est pratique de trier vos cartes au fur et à mesure que vous les piochez.


== Enchères

Les enchères déterminent le joueur qui jouera le patron contre les deux autres.
Les enchères possibles sont 1, 2 et 3.
Le joueur qui a pioché la carte face visible du paquet est le premier à parier.
Chaque joueur, en sens anti-horaire, peut ensuite soit passer, soit parier plus que la précédente enchère.
Si tout le monde passe, les mains sont défaussées et la distribution est recommencée.
S'il y a une enchère, les enchères continuent jusqu'à ce que deux joueurs aient passé, ou qu'un joueur ait enchéri 3, ce qui met fin aux enchères puisqu'il s'agit de la plus haute enchère possible.
L'enchérisseur final est le patron.

Le patron révèle les 3 trois cartes face cachées au centre de la table pour que tout le monde les voient avant de les ajouter à sa main pour un total de 20 cartes.


== Jeu

Le patron joue en premier, et peut joueur une carte seule ou n'importe quelle combinaison légale.
En sens anti-horaire, chaque joueur suivant doit soit passer (sans jouer de carte), soit joueur une combinaison plus haute de *même nombre de cartes* et de *même type*.
Il y a juste deux exceptions à cette règle : un *missile* bat toutes les combinaisons, et une *bombe* bat toutes les combinaisons sauf une bombe plus haute et un missile - voir les définitions plus bas.
Le jeu continue autour de la table pour autant de tours que nécessaire jusqu'à ce que deux joueurs consécutifs aient passés.
Les cartes jouées sont alors défaussées face cachées et le joueur qui a joué les dernières cartes re-commence avec une carte ou n'importe quelle combinaison.

Il y a treize types de combinaisons possibles :

. *Carte Seule :* +
  Allant de trois (le plus bas) jusqu'au Dragon (le plus haut) comme expliqué ci-dessus.

. *Paire :* +
  Deux cartes de même valeur, de trois (le plus bas) jusqu'à deux (le plus haut).

. *Triple :* +
  Trois cartes de même valeur, de trois (le plus bas) jusqu'à deux (le plus haut).

. *Triple avec une carte attachée :* +
  Un triple avec une carte seule ajoutée, par exemple 6-6-6-8.
  Leur valeur est celle des cartes du triple - donc par exemple 9-9-9-3 bats 8-8-8-A.

. *Triple avec une paire attachée :* +
  Un triple et une paire, comme un full au poker, leur valeur étant celle des cartes du triple - par exemple Q-Q-Q-6-6 bats 10-10-10-K-K.

. *Suite :* +
  Au moins 5 cartes de valeur consécutives, de trois jusqu'à l'as - par exemple 8-9-10-J-Q.
  Les deux et les jokers ne peuvent pas être utilisés.

. *Suite de paires :* +
  Au moins trois paires de valeurs consécutives, de trois jusqu'à l'as.
  Les deux et les jokers ne peuvent pas être utilisés.
  Par exemple 10-10-J-J-Q-Q-K-K.

. *Suite de triples :* +
  Au moins deux triples de valeurs consécutives, de trois jusqu'à l'as.
  Les deux et les jokers ne peuvent pas être utilisés.
  Par exemple 4-4-4-5-5-5.

. *Suite de triples avec des cartes attachées :*
  Une carte supplémentaire est ajoutée à chaque triple.
  Par exemple 7-7-7-8-8-8-3-6.
  Les cartes attachées doivent être différentes de celles des triples et entre elles.
  Bien que les triples de deux ne puissent pas être inclus, un deux, un joker, ou un deux et un joker peuvent être attachés, mais pas les deux jokers.

. *Suite de triples avec des paires attachées :*
  Une paire supplémentaire est ajoutée à chaque triple.
  Seuls les triples doivent se suivre - par exemple 8-8-8-9-9-9-4-4-J-J.
  Les paires doivent être de valeur différente entre elles.
  Bien que les triples de deux ne puissent pas être inclus, une paire de deux peut être attachée.
  Notez que vous ne pouvez pas mixer les cartes et les paires attachées - par exemple 3-3-3-4-4-4-6-7-7 n'est pas valide.

. *Bombe - quatre cartes de même valeur :* +
  Une bombe peut tout battre, à l'exception d'un missile.
  Une bombe plus élevée bat une bombe plus basse.

. *Missile - la paire de jokers :* +
  C'est la combinaison la plus haute qui bat toute les autres, dont les bombes.

. *Ensemble de Quadruple :* +
  Il y en a deux types :
+
--
.. Un carré avec deux cartes de valeur différentes attachées, comme 6-6-6-6-8-9.
.. Un carré avec deux paires de valeur différentes attachées, comme J-J-J-J-9-9-Q-Q.
--
+
Les deux et les jokers peuvent être attachés, mais vous ne pouvez pas utiliser les deux jokers dans un ensemble de quadruple.
Les ensembles de quadruples ont la valeur des cartes de leur carré.
Notez qu'un ensemble de quadruple ne bat qu'un ensemble plus bas du même type, et ne peut battre aucune autre combinaison.
+
CAUTION: *Un ensemble de Quadruple n'est pas une bombe* et peut donc être battue par une bombe faite de cartes plus basses.

Notez que passer ne vous empêche de jouer à votre prochain tour.

.Main
====
Le joueur A (le patron) ouvre avec 3-3-3-9 pour se débarrasser de quelques cartes basses.
Le joueur B passe.
Le joueur C joue 5-5-5-7, le joueur A joue K-K-K-J et le joueur B joue A-A-A-3.
C et A passent, B peut donc démarrer avec ce qu'il souhaite.
Il ouvre avec un simple 4.

NOTE: B aurait pu jouer ses as lors de son premier tour, mais a préféré passer pour donner l'opportunité à son partenaire de se débarrasser de quelques cartes.
Une fois que B a passé, C devrait jouer s'il le peut, afin de ne pas laisser au patron (A) une nouvelle ouverture gratuite.
Après avoir battu la seconde combinaison de A, B ouvre avec une carte basse pour donner à C le choix de jouer une autre carte indésirable ou de mettre la pression au patron en jouant une carte élevée.
====


== Points

Si le patron se débarrasse de toutes ses cartes avant les deux autres joueurs, il remporte la manche et chaque adversaire lui paye la valeur de son enchère - 1, 2 ou 3 points - à condition qu'aucune bombe ou missile n'ait été joué.
Si l'un des deux autres joueurs se débarrasse de toutes ses cartes avant le patron, le patron perds et dois payer la valeur de son enchère *à chaque adversaire*.

À chaque fois qu'un joueur a joué une bombe ou un missile, le payment pour la manche est doublé.
Par exemple, lors d'une manche au cours de laquelle deux bombes et un missile ont été joués, un joueur ayant enchéri 3 gagnera 24 points de chaque adversaire s'il a gagné ou donnera 24 points à chaque adversaire s'il a perdu.

NOTE: Puisque chaque adversaire du patron gagne ou perd autant, ils forment un partenariat temporaire.
Lorsqu'ils jouent contre le patron, il est aussi profitable d'aider votre partenaire à se débarrasser de ses cartes que de gagner par vous-même.
Les partenaires vont donc éviter de se battre mutuellement et le partenaire le plus faible s'attachera à aider le partenaire le plus fort.

Un nombre de manches prédéterminé peut être jouées pour déterminer le grand gagnant.
