= Tichu
:toc: preamble
:toclevels: 4
:icons: font

A traditional Chinese game.

.Components
****
* 52 numbered cards: 1-13 in ♠, ♥, ♣ & ♦.
* 4 special cards:
** The *0★*.
** The *Owl*.
** The *Wolf*.
** The *Monkey King*.
* 6 combinations reference cards.
* 6 special cards reference cards.
****


== Tichu Nankin (4 joueurs)

*The game is played by pairs of two partners* with the players of each team sitting opposite one another.
During the game, the partners try to help each other score points and gain the lead.


=== Distribution & push

Before the game starts, the players choose a starting player who shuffles the cards for the first hand and offers the shuffled deck to the player on his left, who may cut the deck.
In subsequent hands, the winner of the previous hand shuffles the deck and offers it to be cut.
The player then places the deck face down in the middle of the table.
The Chinese do not deal cards, but rather, they take them.
The dealer starts by taking the top-most card.
Then, all take turns, in counter-clockwise order, taking one card at a time, until the deck is exhausted and each player holds a fan of 14 cards in his hand.
As in most card games, the players keep their cards secret from each other, including their partners.

Next, the players each push 3 cards, 1 to each other player.
They push the cards face down.
Once a player has pushed 3 cards, he may pick up the cards pushed to him, adding them to his fanned hand.


=== Le jeu

The player holding the 0★ begins by leading (playing face up on the table) any of the following combinations of cards from his hand:

[options="autowidth",frame=none,grid=none]
|===
| combination | example

a| * A single card | 4
a| * A pair of cards +
(of equal rank) | 8,8
a| * A sequence of pairs +
of adjacent value | 4,4,5,5 +
11,11,12,12,13,13
a| * A trio of cards +
(of equal rank) | 2,2,2
a| * A full house +
(trio + pair) | 5,5,5,9,9
a| * A sequence of at least 5 cards +
of consecutive value | 4,5,6,7,8,9
|===

The next player (to the right - the Chinese play to the right, like the Swiss and the Hopi) now has the choice of:

* Passing.
* Playing a similar combination of higher value.

A single card can thus only be beaten by a single card of higher value, a sequence of two pairs only by a sequence of two higher pairs, a sequence of eight cards only by a higher sequence of exactly eight cards, a full house only by a higher full house (in full houses the value of the trio is what counts).

Exception: Bombs (see below).

Play continues to the right.
As soon as 3 players pass in turn order, the player who played the last (highest) combination gathers in the trick and leads a new combination.
If this player has no cards left, he has “gone out” and the right to lead passes to his right-hand neighbor (passing further to the right if the latter has gone out as well).


=== Special cards

The *0★* is an interesting card of mixed reputation, with the following properties:

* Its owner starts the hand (but need not lead the 0★).
* The 0★ ranks as a 0 and is, therefore, the lowest card in the deck.
As a zero, it may be included in a suitable sequence (e.g. 0,1,2,3,4).
* When a player plays the 0★, he is allowed to wish for a certain rank (for example an 8 or an Ace, but not a special card).
The next player who has a card of the desired rank, and can lawfully play it, must play it (possibly in a bomb! or rarely in a sequence).
A player who does not hold or cannot play a card of the desired rank can play any lawfull card or pass. +
The wish remains in force until someone fulfils it.

The faithful *Owl* has no trick-taking power at all. +
It can only be played by leading it as a single card and it transfers the right to lead to the player’s partner.
If the player’s partner has already gone out, the lead passes to the partner’s right.

The ever-changing *Wolf* is the most powerful card in Tichu. +
However, it counts minus 5 points.
It can be played:

* as a joker – it can take the place of any normal card in a combination, but may not be used to make a bomb!
* as a single card.
It's value is half a rank higher than the card it's played after.
If an eight is the current highest card played, the Wolf counts as 8.5, and can be beaten by a nine or higher.
The Wolf can beat an 13, but not the Monkey King.
If led, the Wolf counts as 1.5.

The *Monkey King* is the highest individual card and is worth 5 points. +
When single cards have been played, it is higher, even than an 13 or 13.5 (the Wolf over a 13), and can itself only be beaten by a bomb.
However: it cannot be part of a sequence.

If the noble *Monkey King* wins a trick, he gives the trick (including its own 5 points) to the opponent of its holder’s choice.


=== Bombs

A Bomb is:

* a sequence of at least five consecutive cards in the same suit.
* or all four cards of the same rank.

Bombs can be played at any time, even out of turn, to take a trick.
They beat anything, be it a single card or a combination.
A higher bomb will beat a lower bomb, so a bomb can be played on a bomb.
The rank of bombs is determined: (1) by the number of cards and (2) by the rank of the cards.
A player can even lead a bomb when leading a new trick.


=== End of a round

The round ends immediately when only one player has cards left in his hand.

Then the tailender (the last player with any cards) hands over the cards remaining in his hand to his opponents and the tricks he won to the winner (the player who has gone out first in the hand).
Next, the round is scored.

* +2 for each 9 and 13
* +1 for each 4
* +5 for the Monkey King
* -5 for the Wolf
There are, thus, 20 points for the whole hand, which are divided between the two teams.

If, however, the two players on one team achieve a double victory (being both first and second to run out of cards), the round ends immediately, the counting is skipped, and this team  scores 40 points.


=== The tichus!

A Tichu is a way for players to score even more points, but with a risk.


==== Small Tichu

Each player may, until he plays his first card in a hand, call "small tichu".
If he then wins the round (going out first) his team gets 20 extra points.
If he does not go out first in the hand, his team loses 20 points.

Calling tichu is an individual undertaking.
The partners cannot discuss it nor arrrange it beforehand.
Once called, of course, his partner may play to help him during the play of the cards, but they still cannot discuss strategy as they play.
And, the tichant himself must go out first.
If his partner goes out first, the team loses the 20 points!
Also, the 20 points for tichu are scored independently of, and in addition to, the normal scoring of the hand.

Also, a player can call "tichu" long before the player plays his first card.
A call before the cards are pushed can be useful as a request for a partner to push over his best card.

==== Grand Tichu

Of course, where there is a small tichu, there must be a grand tichu, as well.

An especially brave or desperate player may, before taking his ninth card from the deck at the beginning of the hand, call “grand tichu”.
If he then goes out first in the hand, his team scores 40 extra points.
If not, his team loses 40 points, as in the rules for his smaller brother.


=== End of game

The team which reaches (or exceeds) a total score of 200 points at the end of a round wins the game.
If both teams are over 200, the team with the most points wins.
In case of a tie, the game continues until a team has 200 or more at the end of a round and there is no tie.


=== Tactical tips

For hints on tactics, it is best to ask a Chinese bus driver.
Since such a person may not be available to all reading these rules, we offer the following from our small experience.

* First, try to get rid of your rotten cards (low singletons and pairs).
Also, be sparing with your aces, Monkey King, and Bombs early in the hand.
A player who has a singleton 4 after a dazzling display of power, was either the victim to an unexpected Bomb or does not understand the game yet.
* Keep an eye on the score.
If the score is, for example 630:970, a grand tichu is begging to be called.
* Unreservedly support your partner’s “tichu”.
When playing the 0★, do not demand a card which might break up your partner’s bomb and do not take his trick (this is certainly legal, but it is likely dangerous unless very low ranks are involved)
* Try to bring down an opponent’s “tichu" when the tichant is the player to his left by making him take his tricks expensively.


=== Frequently Asked Questions

* *Can the Owl be bombed?* +
No, Bombs cannot be used to take the Owl (and the right to lead).
Bombs can only be played (even out of turn) on a card combination (or single card) on the table.
You may bomb your own trick, if you want.
When 3 players pass in turn order, any player may bomb before the trick is considered over.

* *When can a bomb be played on a 0★?* +
The best way to answer is with an example.
+
====
Player 1 leads the 0★ and wishes an 8.
Between Player 1 and 2 (out of turn) all players (including players 1 and 2) may bomb (without fullfilling the wish).

When player 2 has a hand like 2,3,4,5,6,7,8,9,10,11,12,12,12,12 he may (before his turn) play the 12-bomb.
After all other players have passed, he must lead the next trick (and fulfill the wish) with his sequence.
If another player had a sequence bomb with an 8 he'd have to play it over the 12-bomb in his turn.
====

* *When must a player fullfill the wish of the 0★?* +
In his ordinary turn only.
A player does not need to fullfill a wish of the 0★ when playing a bomb out of turn.
However, if he wins the trick with the bomb, he has to lead the next trick and must fullfill the wish then (see also the example above).

* *Does the Monkey King give away a bombed trick?* +
No. As the Monkey King did not win, he does not control the trick.

* *Do I have to use the Wolf to fulfill a wish?* +
If a player does not have a card of the desired rank, he is not obliged to fullfill the wish even if he has the Wolf (which is not considered a card of the desired rank, even though it can be a joker).
The next player who has a card of the desired rank and can lawfully play it, must play it.
Even if he has to play a bomb or a sequence of appropriate length with the Wolf.

* *What happens to the last trick of the hand (when the 3rd player plays his last card(s))?* +
The trick is ended immediately, but is still given away if won by the Dragon.

* *What happens if two players want to play a bomb at the same time?* +
This happens very rarely and the solution of the problem is usually obvious.
+
However (if you need a rule): Tichu should not be a game of reaction, fast play should not give any advantage: bombs can be played before ordinary combinations and multiple bombs can be played in order of play.
BUT: if a player after 5 seconds of thinking decides to play the Monkey King, no other player can claim to play a bomb at the same time (and therefore before the Monkey King).
If a player wants more time to think about his play, whether it is his turn or not, he must ask the other players to wait until his considerations are done.

* *What if two players of the same team call a Tichu at the same time?* +
This is a problem with online games, but very rare in normal games.
In a tournament, I'd say that the second player, in turn order, may withdraw his Tichu if he wishes.
However, do not allow players to claim having called a Tichu at the same time, unless it was really simultaneous.
If there is a delay, the two Tichus stand, giving that team a serious problem.

* *Is 3,3,3,3,Wolf a valid full house?* +
No.
This case is not covered by our rules, but we require the owner of a bomb and the Wolf to play his hand without this strange kind of full house.

* *Can I play a sequence-bomb as a normal sequence?* +
No.
This is also not covered by the rules, but who wants to give preference to those lucky players always having bombs?

* *Can we play in clockwise order instead?* +
Yes, if you are more comfortable with clockwise order of play, please use that instead.
Just change all the rules to switch the direction of play.
If you are also more comfortable dealing the cards instead of taking them, then have the person who shuffles the cards also deal them.


== Threechu (Tichu Nankin - 3 players)


=== Le jeu

Shuffle and take cards as you would for a four player game.
The shuffler plays with a dummy partner.

The shuffler may not declare Grand Tichu for either himself or the dummy.

Before any cards are pushed, the dealer may look at both his hand and the dummy’s.

Pushing cards is the same as in a four player game, except that players only push cards to their oponents (two cards instead of three are pushed).

After cards are pushed, place the dummy face up on the table.
The shuffler plays on the dummy's behalf.
The dealer may declare Small Tichu on behalf of the dummy before he plays the first card from the dummy.
The dummy  does not have to fullfill any wish.


=== Score

Scores are kept individually, even for the dummy.
Each player in a partnership receives the same number of points that the team would receive if it were a four player game.
The shuffle (and partnership with the dummy) passes to the left after each hand.

The game ends after a certain number of hands (divisible by three).
We do not recommend a game to 200 points, as the dummy player is likely to win such a game


== Tichu Tientsin (6 joueurs)

Tientsin (Tianjin) tichu is played six handed with two teams of three seated alternating around the table.

The rules of the game are the same as for the four handed version, except that:

* Grand tichu must be announced before the seventh card is taken.
* Each player pushes only two cards, to his own partners and gets one card back from each of them.
* The Owl transfers the right to lead to its holder’s choice of partner.
* In the scoring, the last loses not only his remaining cards but also all his tricks to the opposition;
the fifth (the second to last to go out) gives his tricks to the winner of the round.
* There is no special reward for a double victory, but a triple victory (one team gets rid of all its cards while all three opponents still hold cards) scores 60 points.
