= Fiasco
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

[.ssd-components]
.Matériel
****
* 48 cartes numérotées : 1-4 & 6-8 à ♠, ♥, ♣, ♦, ✿ & ★.
* 6 Loups
* 6 Papillons
* 6 cartes couleur : A à ♠, ♥, ♣, ♦, ✿ & ★.
****

Le but de Fiasco est de collecter toutes les cartes d'une couleur pour marquer le plus de points en gagnant des plis, tout en empêchant vos adversaires d'en faire de même.


== Mise en Place

Chaque joueur·euse reçoit une carte Couleur et la place face visible devant lui·elle.
Cette carte représente la couleur qu'il·elle collecte.


== Jouer une manche

Chaque joueur reçoit d'abord 6 cartes face cachées.
Les cartes restantes de la pile sont placées face cachées près de celui·celle qui distribue.
Les joueur·euse·s regardent les cartes de leur main.

Puis, en commençant par le·la joueur·euse à gauche de celui·celle qui a distribué (en sens horaire), chaque joueur·euse place une carte de sa main au centre de la table.
Celui·celle qui a placé la carte de plus haute valeur remporte le pli et toutes ses cartes.
Si le pli contiens une carte de la couleur qu'il·elle collecte, il·elle place alors cette carte face visible dans sa collection.
Les collections sont placées sur la table juste devant chaque joueur·euse et seront utilisées pour le scoring plus tard.
Toutes les autres cartes du pli sont défaussées.

Le·la joueur·euse qui a remporté le dernier pli doit ouvrir le pli suivant.
Le jeu continue ainsi avec la carte la plus haute remportant le pli et son·sa gagnant·e ouvrant le suivant.

NOTE: Les cartes de couleur ne peuvent pas aller directement de la main d'un·e joueur·euse dans sa collection.
      Les cartes collectées doivent d'abord être gagnées dans un pli.

Vous pouvez jouer la carte de votre choix.
Il n'y a pas d'atout et toutes les couleurs sont de même rang.
Vous n'êtes pas obligé de suivre la couleur.
Si vous voulez remporter le pli, jouez une carte de forte valeur.
Jouez une carte de faible valeur pour l'éviter.


=== Loups

Le loup est la plus haute carte du jeu et est aussi une manière de remporter des points, peu importe la couleur qu'un·e joueur·euse collecte.
Lorsqu'un·e joueur·euse remporte un pli contenant un Loup, ce Loup est alors placé dans sa collection et lui marquera des points.


=== Papillons (cartes Fiasco)

Les cartes Papillon (Fiasco) sont considérées de rang 5, il y a donc autant de cartes qui lui sont supérieures que de cartes qui lui sont inférieures.
Lorsqu'un·e joueur·euse remporte un pli contenant un Papillon, il·elle perd alors une carte de sa collection pour chaque Papillon dans le pli.
Si un·e joueur·euse doit perdre plus de carte qu'il·elle n'en possède dans sa collection, il·elle perd uniquement ce qui est disponible.
Les pertes ne sont pas déportées au pli suivant.

Essayez de vous débarrasser de vos cartes Papillons en les infligeant à vos adversaires.
Ainsi, commettez un Fiasco !

=== Égalités

Si celui·celle qui remporte le pli ne peux être déterminé parce qu'il y a plusieurs cartes de plus haute valeur, il y a alors une 'égalité haute' et des cartes supplémentaires doivent être jouées.
Les cartes au centre de la table le restent, et n'ont pas d'incidence sur le prochain pli.

Chaque joueur·euse place une autre carte au centre de la table pour déterminer le·la gagnant·e du pli.
Celui·celle qui remporte ce pli remporte toutes les cartes au centre de la table.
En cas de seconde 'égalité haute', les plis continuent jusqu'à ce qu'il y ait un·e gagnant·e.

En cas d'égalité alors que les joueurs n'ont plus de carte en main, des cartes supplémentaires sont distribuées.
La seule exception à cette règle est lorsqu'une égalité haute a lieu à la dernière main avant la marque, les cartes sont ignorées et défaussées avant le marquage des points.

=== Re-distribution

Une fois les six cartes initiales jouées, on distribue six nouvelles cartes du paquet à chaque joueur·euse et le jeu continue.
S'il n'y a pas assez de cartes dans le paquet, chaque joueur·euse reçoit un nombre égal maximum de cartes.
Les cartes restantes sont défaussées.

Une fois toutes les cartes du paquet jouées, la défausse est mélangée et re-distribuée.
Le rôle de celui·celle qui distribue change à chaque nouveau paquet, en sens horaire.

Le paquet est intégralement distribué trois fois avant de compter les points.


=== Points

Une fois le paquet joué intégralement trois fois, le jeu s'arrête et chaque joueur·euse compte les cartes dans sa collection.
C'est la marque.

* 2 points par carte couleur collectée.
* 1 point par Loup collecté.
* 4 points bonus si vous avez les six Loups.
* 6 points bonus si vous avez les sept cartes de votre couleur.

Une fois les points comptés, toutes les cartes sont remélangées.
Les joueur·euse·s collectent toujours les mêmes couleurs.
Les points de chaque marque sont additionnés pour déterminer le score total de chaque joueur·euse.


== Remporter le jeu

*Partie Rapide* : Celui·celle avec le meilleur score à la première marque remporte la partie.

*Partie Complète* : Le·la première joueur·euse à avoir un score supérieur ou égal à 42 points remporte la partie.
