= Papayoo
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

Un jeu traditionnel.

.Matériel
****
* 40 cartes de couleur : 1-10 à ♠, ♥, ♣ & ♦.
* 20 cartes Payoo : 1-20 à ★.
* 12 cartes de sélection du Papayoo: 3 **K** à ♠, ♥, ♣ & ♦.
****


Mélangez ensemble les cartes de couleur et les cartes Payoo (★) pour former la pile de carte de jeu.

Placez les cartes *K* en une pile séparée pour former la pile de sélection du Papayoo.


== Valeur des cartes

Chaque Payoo (★) vaut sa propre valeur soit 1 à 20 points; l’un des quatre 7 (♠, ♥, ♣ ou ♦) est le Papayou : il change à chaque donne et vaut 40 points.
Les autres cartes n’ont aucune valeur.


== But du jeu

Récolter aussi peu de points que possible.


== La donne

Le donneur change à chaque tour ; il distribue les cartes conformément au tableau ci-dessous (par exemple à 3 joueurs, il distribue alternativement à chacun six fois trois cartes puis une fois deux cartes).
À 7 ou 8 joueurs, il faut retirer les 1 du jeu avant la partie.

[%autowidth]
|===
| Nombre de joueurs | Cartes à retirer avant la partie | Nombre de cartes par joueur (distribution) | Écart (voir plus bas)

>| 3 .4+^.^| aucune | *20* (6x3 + 1x2) | 5
>| 4 | *15* (5x3) | 5
>| 5 | *12* (4x3) | 4
>| 6 | *10* (3x3 + 1x2) | 3
>| 7 .2+^.^| *1* de ♠, ♥, ♣ & ♦ | *8* (2x3 + 1x2) | 3
>| 8 | *7* (2x3 + 1x1) | 3
|===


=== L’écart

Après avoir rangé leurs jeux, les joueurs procèdent à l’écart.
Chacun se débarrasse des cartes de son choix en retirant de son jeu le nombre de cartes précisé sur le tableau et les pose, faces cachées, devant son voisin de gauche.
Il est impératif de donner l’écart à son voisin de gauche avant de prendre connaissance des cartes de l’écart arrivant de son voisin de droite.


=== Le tirage au sort du Papayoo

Quand tous les joueurs ont procédé à l’écart, le donneur mélange les cartes de sélection du Papayoo (les cartes *K*), en tire une aléatoire, et la place face visible sur le dessus de sa pile, déterminant ainsi la couleur du Papayoo.
Si par exemple c'est le  *K♠* qui est tiré, le 7 de ♠ est le Papayoo et vaut 40 points pour cette manche.


== Déroulement d’une manche

Le donneur entame le premier pli en plaçant la carte de son choix, face visible, au centre de la table.
Les autres joueurs jouent ensuite chacun à leur tour dans le sens horaire, en suivant impérativement la couleur demandée par le premier (mais il n’est pas impératif de jouer une carte de plus forte valeur).
Le Payoo (★) est une cinquième couleur, au même titre que le ♠, ♥, ♣ ou ♦.
Si un joueur n’a pas en main de la couleur demandée, il se défausse de toute autre carte de son choix.
Celui qui a joué la plus forte carte dans la couleur demandée ramasse le pli et entame le pli suivant.
Si aucun joueur ne peut suivre dans la couleur demandée, c’est le joueur qui a entamé qui ramasse le pli.


== Fin d’une manche

A l’issue du dernier pli, les joueurs comptent leurs points.
Chaque Payoo (★) vaut sa propre valeur, le Papayoo vaut 40 points et les autres cartes ne valent rien.
Le total des scores de la manche doit faire 250.
On additionne ces points à ceux des donnes précédentes.


== Fin d’une partie

Les joueurs fixent en début de partie le nombre de manches qu’ils souhaitent jouer (4 manches durent environ 30 minutes).
Celui qui a le moins de points à l’issue de la dernière manche est déclaré vainqueur.


== Notes

Au moment de l’écart, il ne faut pas oublier qu’écarter totalement une couleur pour se créer de meilleures possibilités de défausse, c’est aussi prendre le risque de se retrouver avec un 7 et/ou un 9 et/ou un 10 « secs » provenant de l’écart du voisin !

Pour éviter de faire un pli, il est souvent tentant de jouer des cartes inférieures à celles des joueurs précédents ; il faut pourtant savoir « prendre quelques points » dès les premiers tours, quand l’enjeu n’est pas trop lourd, pour se débarrasser de ses plus fortes cartes et en garder de plus faibles pour les tours suivants; cela peut même être très opportun pour le dernier joueur, car il connait clairement la valeur du pli.
