= Haggis
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

Un jeu de Sean Ross.

.Matériel
****
* 45 cartes numérotées : 2-10 à ♠, ♥, ♣, ♦ & ✿.
* 9 cartes spéciales : 3 Papillons, 3 Serpents & 3 Loups.
****

Le but de ce jeu est de se défausser de ses cartes avant les autres joueurs, tout en capturant le plus possible de cartes à points.
Des points supplémentaires peuvent être gagnés en pariant que l’on sera le premier à se défausser de ses cartes.

Un jeu de Haggis contient 54 cartes réparties de la façon suivante : les valeurs 2 à 10 en cinq couleurs, plus trois Papillons (P), trois Serpents (S) et trois Loups (L).
L’ordre des cartes, de la plus faible à la plus forte, est : 2, 3, 4, 5, 6, 7, 8, 9, 10, P, S, L.


== Préparation d’une manche

IMPORTANT: À deux joueurs, retirez toutes les cartes de la couleur ✿, ainsi qu’un Papillon, un Serpent et un Loup avant de commencer à jouer.

Un jeu de Haggis se joue en plusieurs manches (mains).
Pour la première manche, choisissez un donneur.

Placez un Papillon, un Serpent et un Loup face visible devant chaque joueur ; ils servent de joker.

Mélangez les cartes et distribuez-en 14 face cachée à chaque joueur.
La main d’un joueur est composée de ces 14 cartes, qui sont prises en main, ainsi que des trois cartes joker qui restent face visible devant lui jusqu’à être jouées.

Les cartes restantes (huit à deux joueurs, trois à trois joueurs) forment le Haggis et sont écartées face cachée.


=== Les paris

Les joueurs peuvent parier qu’ils seront le premier à « sortir » (c'est-à-dire à se défausser de leur main).
Un joueur peut parier une seule fois, tant qu’il n’a pas encore joué de carte.
Les paris possibles sont de 0 point (pas de pari), 15 points (Petit Pari) ou 30 points (Grand Pari).

Tous les joueurs peuvent placer un pari, du montant qu’ils veulent.

Aucun pari ne peut être retiré ou modifié.


== Déroulement d’une manche

Chaque manche se joue en un certain nombre de plis.
Pour la première manche, le joueur à gauche du donneur commence en posant une première combinaison.
Une combinaison peut être une famille, une suite ou une bombe.


=== Familles

Une famille est un groupe de cartes de même valeur.
Les familles contiennent ainsi de une à huit cartes (carte unique, paire, brelan, etc.,).

.Familles
====
♣8 = Unique. +
♠8 + ♦8 = Paire. +
♥8 + ♦8 + ♣8 = Brelan. +
♥8 + ♦8 + ♣8 + ♠8 + ✿8 + P = 6 de même valeur avec joker.
====


=== Suites

Une suite est un groupe d’au moins trois cartes uniques ou d’au moins deux familles plus grandes (paires, brelans, etc.), de valeurs consécutives et de couleurs identiques d’une famille à l’autre.

.Suites
====
♥7 + ♥8 + ♥9 = Suite de 3 cartes uniques (7-8-9). +
♥10 + P + S = Suite de 3 cartes uniques (10-P-S). +
6♣, 7♣, S, ♣9, 10♣, P = Suite de 6 cartes uniques (6-7-8-9-10-P, avec joker).

♥8 + ♦8 + ♥9 + ♦9 = Suite de 2 paires. +
♥7 + ✿7 + ♥8 + ✿8 + ♥9 + ✿9 = Suite de 3 paires. +
♥8 + ♦8 + ♣8 + ♠8 + ♥9 + O + ♣9 + ♠9 = Suite de 2 carrés avec joker.
====


=== Jokers

Les Papillons, Serpents et Loups peuvent aussi être utilisés comme joker dans une famille ou une suite pour remplacer n’importe quelle carte de valeur inférieure (exemple : un Papillon peut remplacer un 8, mais pas un Loup).

Quand un joker est inclus dans une suite, il prend la couleur désirée.

NOTE: Les cartes P, S et L ne sont pas forcément jouées comme jokers ; elles peuvent être jouées comme carte unique, ou dans une autre famille ou une suite. +
Exemple : P bat un 10 joué comme carte unique ; 9-10-P bat 8-9-10 ; 10-10-P-S (où le P est "naturel" et S un joker) peut être joué comme suite pour battre 9-9-10-10.

Une famille de plus d’une carte ou une suite ne peuvent pas contenir uniquement des jokers (une combinaison de deux ou trois jokers est une bombe).


=== Bombes

Une bombe est une combinaison spéciale de cartes à points, dont l’usage est détaillé ci-dessous (voir <<plis>>).
Il existe six types de bombes.
De la moins forte à la plus forte :

* 3-5-7-9 (en quatre couleurs différentes, sans jokers)
* P-S
* P-L
* S-L
* P-S-L
* 3-5-7-9 (dans la même couleur, sans jokers).


[[plis]]
== Plis

Après la pose d’une combinaison de cartes, le joueur suivant dans le sens des aiguilles d’une montre doit soit jouer une combinaison plus forte, soit passer.
Un joueur peut choisir de passer même s’il possède une combinaison plus forte que la précédente.

Pour qu’une combinaison soit plus forte qu’une autre, elle doit être du même type et posséder le même nombre de cartes, mais avec des rangs plus élevés.
Ainsi, seule une carte unique peut être jouée après une carte unique ; si une paire est posée, seule une autre paire plus forte peut être jouée ; un brelan ne peut être battu que par un autre brelan plus fort, etc.

Les bombes sont l’unique exception à cette règle : elles peuvent être jouées pour battre toute autre combinaison, à l'exception d’une bombe égale ou plus forte.
Une fois qu’une bombe a été jouée, seules d’autres bombes, plus fortes, peuvent être jouées.

Chaque joueur continue ainsi de jouer des combinaisons de plus en plus fortes du même type et du même nombre de cartes ou des bombes, jusqu’à ce que les autres joueurs passent successivement.

Dans le jeu à deux, cela correspond à l’un des joueurs qui passe.

Dans le jeu à trois, cela correspond à deux joueurs qui passent successivement.
(Un joueur qui passe peut continuer de jouer jusqu’à ce que le pli soit remporté.)

À ce moment, le joueur qui a joué la combinaison la plus forte remporte le pli.
Si la combinaison la plus forte n’était pas une bombe, le gagnant reçoit les cartes du pli.
Si c’est une bombe, elles sont données par le gagnant du pli à l’un de ses adversaires, qu’il choisit.

Le gagnant du pli a la main : il pose la première combinaison du pli suivant.
À trois joueurs, s’il vient de sortir (vient de poser sa dernière carte), le joueur à sa gauche commence.


== Fin d’une manche

Dès que tous les joueurs sauf un ont défaussé leurs cartes, la manche se termine immédiatement.

Le joueur qui a posé la dernière combinaison reçoit les cartes du pli final, sauf si cette combinaison est une bombe, auquel cas les cartes sont capturées comme indiqué dans la section <<plis>>.
Le dernier joueur ne jouera pas les cartes qui lui restent en main.


== Scoring

Les points gagnés proviennent :

1. des cartes restant dans la main de vos adversaires,
2. des cartes à points capturées dans des plis, et
3. des paris.

Un joueur qui est sorti marque 5 points pour chaque carte du joueur qui en possède le plus au moment de la pose de sa dernière carte.

Toutes les cartes à points (3, 5, 7, 9, P, S et L) reçues dans les plis rapportent à leur gagnant leurs points :

[options="autowidth"]
|===
h| Carte  | 3 | 5 | 7 | 9 | P | S | L
h| Points | 1 | 1 | 1 | 1 | 2 | 3 | 5
|===

Les points des paris sont ensuite comptés.
Les points d’un pari gagné sont ajoutés au score du parieur.
Un pari perdu est ajouté au score du premier joueur à être sorti, et à ses adversaires qui n’ont pas parié pour la manche en cours.

.Points des paris
====
Adam, Brenda et Carole jouent.

Adam et Brenda font tous deux un Petit Pari après avoir reçu leurs cartes.
Carole ne parie pas.

Adam est le premier à sortir.
Il remporte donc son pari et gagne 15 points.
Il gagne aussi 15 points supplémentaires grâce au pari perdu de Brenda, pour un total de 30 points.
Brenda ne gagne aucun point grâce aux paris.
Carole gagne 15 point grâce au pari raté de Brenda.

Avec ces mêmes paris, si Carole était sortie en premier au lieu d’Adam, elle aurait gagné 30 points : 15 pour chacun des paris perdus d’Adam et Brenda.
Les autres joueurs ne recevraient aucun point grâce aux paris.
====

NOTE: Dans un jeu à trois, le premier joueur à sortir, c'est-à-dire à s’être défaussé de ses cartes, doit noter immédiatement le nombre de cartes du joueur qui en possède le plus.
Notez que les jokers d’un joueur font partie de sa main.


== Suite du jeu

Après avoir ajouté les points de la manche en cours au total de chaque joueur, une nouvelle manche commence et les cartes sont à nouveau distribuées.

Le donneur est le joueur qui possède le plus de points.
En cas d’égalité, le gagnant de la dernière manche distribue les cartes.

Le joueur qui possède le moins de points pose la première carte du pli suivant ; en cas d’égalité, le joueur à gauche du donneur commence.


== Conditions de victoire

Les manches se succèdent jusqu’à ce qu’un joueur atteigne ou dépasse un total convenu à l’avance.
Le joueur qui a le plus de points remporte la partie.
En cas d’égalité, continuez de jouer jusqu’à ce qu’un gagnant unique émerge.

250 points constituent un total adapté à un jeu plus court. +
350 points permettent des parties plus longues.

.Règles de tournoi
****
Dans un tournoi à trois joueurs, ce n’est pas le gagnant qui décide qui capture les cartes.
Un pli gagné grâce à une bombe est pris par le joueur ayant posé la deuxième plus forte combinaison.
Si le pli est formé d’une seule bombe, il revient au joueur situé à la droite de celui qui l’a posée.
****
