= Dealt!
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 49 numbered cards: 1-12 in ♠, ♥, ♣, ♦.
* 2 Butterflies, 2 Monkeys, 2 Wolves.
****

All of you are trying to play your cards as quickly as possible by outbidding the other player’s combinations.
You may play one, two, or three cards each turn—but only if they are next to each other in your hand!

Once you get rid of all your cards you’re safe, because the last player who has cards gets a penalty, and the first player with three penalties will lose this game!
If you fancy a longer game, you can go to 4 penalties.


[[setup]]
== Setting Up the Game

The oldest player shuffles all the cards and deals *ten cards* to each player (*seven cards* if there are 5 players).

CAUTION: *This is the most important rule in the game!*
Don’t take your cards into your hand until you have all ten (or seven) cards in front of you.
Then take them up and fan them out, but *do not* change the order.
During the game, *no player* may change the order of the cards in their hand.

Once all players have received their cards, the oldest player also puts two reserve cards down in front of each player, face up.
Put all remaining cards in the center of the table as a face-down draw pile.


== Playing the game

The player to the left of the dealer begins the first turn.
A round consists of several turns and ends when a player is last with cards in hand.


=== What is a turn?

One after another, in clockwise order, each of you plays one card combination from your hand.
A combination may include one, two, or three cards, but *you can only play cards that are adjacent to each other in your hand*.

If you are the player who begins (opens) a turn, you can play any card combination.
All subsequent players *must* outbid the most recently played combination.


=== What does ‘outbid’ mean?

Each player *must* play a card combination that is ranked higher than the highest combination played so far:
either by playing the same combination with higher numbers, or by playing a higher combination.

*The card combinations are ranked in this order:*

1. *Solo*: a single card.
2. *2-straight*: two cards of neighboring values (ex: 2 & 3).
3. *Pair*: two cards of the same value.
4. *3-straight*: three cards of neighboring values (ex: 3, 4 & 5).
5. *Trips*: three cards of the same value.

IMPORTANT: The two or three cards in your combination must be adjacent to each other in your hand.
The order does not matter, however: 8-10-9 is just as good a 3-straight as 9-8-10 or 8-9-10.

.Turn
====
Andy plays an 8 as a Solo. +
Carla outbids the Solo by playing a 12. +
Nico outbids this by playing a 5 and a 4 that are *adjacent* in his hand as a 2-straight, +
which Susie can outbid by playing a higher 2-straight with her 5 and 6.
====


=== When do the reserve cards come into play?

If you can’t — or don’t want to — outbid a combination, you *must* instead take *one* of your reserve cards into your hand.
When you do, you can place that card anywhere in your hand that you want to.

.Turn
====
Susie plays a Pair of 11’s. +
Andy outbids it with a 3-straight of 6, 7, and 8. +
Carla can’t play a higher combination, so she must take one of her reserve cards.
She chooses the 7.
Carla puts it next to her 6, so she can play both as a 2-straight in a later turn. +
Nico can’t outbid, either, and takes the 12 from his reserve.
====


=== Who wins a turn?

Once all players have either played a card combination *or* taken up a reserve card, the turn ends.
The player who played the highest card combination wins the turn and begins the next turn.
If the winner of a turn does not have any cards left in his or her hand (reserve cards that may still
be in front of the player don’t count), the player who had the second-highest combination begins
the next turn.

If in such a case the winner of a turn was the only player who played a card combination, their
right-hand neighbor begins the next turn.

IMPORTANT: The point of the game is not to win turns, but rather, to get rid of your hand of cards as fast as possible.
All cards which are played in a turn are put on a common discard pile.


=== The special cards

*The Butterfly* can assume any value from 1 to 12.
You may play it on its own or as part of a combination.
However, like other cards, it can only be part of a combination with adjacent number cards.
When you play a Butterfly, you have to call out the value it is supposed to be.

*The Monkey* can only be played on its own.
When you play a Monkey, you immediately end and win the turn, even if some players have not yet played a card combination at this point.

*The Wolf* also can only be played on its own.
When you play it, you don’t have to outbid anyone, so you can always play it.
The player following you must then outbid the combination which was played before your Wolf or take one reserve card.
Both Wolves can be played in the same turn. +
If you win a turn that includes a Wolf, you draw three cards (six cards if both Wolves were played) from the draw pile, one by one, and sort them into your hand one after the other in the position of your choice.

.Turn
====
Andy plays a 12 as a Solo. +
Carla plays a 2-straight with a 7 and a 6. +
Nico plays a 2-straight of 11 and 12, +
and Susie plays her Wolf Card. +
Nico wins the turn.
Because of Susie’s Wolf, he has to draw three new cards from
the draw pile, one by one, and sort them into his hand.
Then Nico starts the next turn.
====


=== End of a Round

If you don’t have any cards left in your hand at the end of a turn (your reserve cards don’t count), you’re out of the current round.
A round ends when only one player has cards left in his or her hand at the end of a turn.
A round also ends if, during a turn, a player can’t outbid the highest combination *and* does not have any reserve cards left to take.
In either case, that player loses the round and gets a penalty point.

There may be cases when, at the end of a turn, several players get a penalty point at the same time.
This happens if all the players still left in the round end up without any cards in their hands after a turn.
In this case, all players who were part of this last turn in the round get a penalty point — except for the winner of the last turn.


=== The Next Round Begins

The oldest player shuffles all the cards again and deals them out as explained under <<setup>>.
The player who got the penalty point opens the first turn of the new round.
If several players got a penalty point at the end of the last round, the first player who lost in last turn order opens the first turn of the new round.


== The End of the Game

When a player receives their 3rd (or 4rth) penalty point, that player loses the game.
Should this happen to more than one player at the same time, they have all lost.

All other players can consider themselves the lucky winners!
