= High Society
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 5 sets of 11 Money cards: 1, 2, 3, 4, 6, 8, 10, 12, 15, Q, K in ♠, ♥, ♣, ♦, ✿
* 16 Status cards:
** 10 Luxury cards: 1-10 in ★
** 3 Prestige Butterfly cards
** 3 Disgrace cards: ★0, ★-‽, Snake
****


You are the cultural elite, the quintessential bon vivants, the true icons of the age.
The competition is fierce amidst highborn and nouveau riche to assert your status and earn prestige in the eyes of your peers.
Adorn yourself with splendid jewellery and high fashion, enjoy fine cuisine and fizzing champagne, and waste away money in casinos and at the races.
Show off your exquisite palette and excellent tastes, but don’t be caught penniless or be cast out as an impostor!
Fashion is fickle but style is forever.
Show them what it really means to be a member of High Society.


== Setup

Give each player a set of eleven money cards of the same colour to keep secret in their hand.
Shuffle the status cards and place them as a face-down deck in the middle of the table.
The player who shuffled the deck starts the game.


== How to Play

Players are socialites trying to live as lavishly and frivolously as possible, outbidding each other to prove they are living life to the fullest.
At the end of the game, the poorest player (or players) will be cast out of the group.
The remaining player who has managed to become the most fashionable, by collecting the highest value status cards, will earn the envy of all and win the game.

Status cards:

* The *luxury cards* are numbered 1 to 10, and increase your status.
* *Prestige cards* (Butterflies) multiply your status, and count down to the end of the game.
* *Disgrace cards* (★0, ★-‽, and Snake) decrease your status in different ways.


== Auction Rounds

At the start of each round, flip the top card of the status deck face-up – this card will now go to the highest bidder.
The starting player must either bid or pass.


=== Bidding

To bid, you must play one or more money cards face-up in front of you and announce the total of all your face-up money cards.
*If you have already bid this round, you can only increase your bid by adding new cards to the ones already on the table* - you cannot pick up cards you have already played.
You can only bid if your new total is higher than the previous bid made this round.

NOTE: The Q and K money cards are valued respectively 20 and 25.


=== Passing

If you don’t want to bid, you may pass instead.
If you have already bid this round, return all of your face-up money cards to your hand.
You may no longer bid this round.

When a player has either bid or passed, the turn moves to the player to their left.
The last remaining player after everyone else has passed wins the auction!
It’s possible (but rare) that everyone will pass without making a bid, in which case the last remaining player gets the card for free.
Place the contested status card face-up in front of the winner.
Discard all the money cards on the table face-down.
*The winner of the auction becomes the starting player for the new round*, and reveals the next status card from the deck.


== Disgrace!

If the revealed status card is a disgrace card, the auction works slightly differently.
This time you are bidding to avoid taking the card, and the round will end as soon as any one player passes.
That player picks up their money cards as usual, but must take the disgrace card and place it in front of them.
*All other players must discard their money cards on the table face-down*.
The passing player starts the next round.


=== Faux Pas (★0)

If a player takes the ★0, they must immediately discard one of the luxury cards in front of them (their choice).
If they currently have no luxury cards in front of them, they must discard the next luxury card they receive.
Once a luxury card has been discarded, discard the ★0 card.

CAUTION: Only cards with a value between 1 and 10 are luxury cards.

Discarded status cards are returned to the box.


=== Passé (★-‽)

The ★-‽ card reduces a player’s status by 5.


=== Scandale (Snake)

The Snake card halves the player’s status at the end of the game.


== Game End

Four cards in the status deck are animals – the three Butterflies, and the Snake.
As soon as the fourth one is revealed, the game ends immediately, with no bidding for the revealed card.


=== Cast Out!

All players reveal their hands and announce the total of their remaining money cards.
The player or players with the least remaining money are cast out, and cannot win!


=== Scoring

Each luxury card awards status equal to its value.
Each prestige Butterfly card doubles the owning player’s status, while the disgrace cards decrease the status.
The player with the highest status that hasn't been cast out wins.

If there is a tie, the player with the most money left wins.
If there is still a tie, the player with the single most valuable luxury card wins.


== Clarifications

* The status cards a player has accumulated are always visible face-up in front of them.
The money cards they have spent are always hidden face-down.
* If you have two prestige cards, multiply your status by four.
If you have all three, multiply your status by eight.

.Scoring
====
Rahul has the following status cards in front of him: ★3, ★9, ★-‽, 2 Butterflies, Snake.

He first adds up his luxury cards for a total of 12.
He then has to lose 5 due to being caught Passé (★-‽), for a total of 7.
Rahul then gets to double his status twice because of his Butterflies, for a total of 28!
Finally, the Snake card halves his status, leaving Rahul with a total of 14.
====
