= Ohio
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 55 cards: 1-10 & K in ♠, ♥, ♣, ♦, ✿
****

Ohio is an exciting card game where cards with lower values are stronger than those with higher values.
All players start with exactly the same cards.
Players take it in turn to play cards of continuously lower values.
The player who finally plays the lowest card wins the trick.
In the end, the player with the highest total value of cards wins the game.


== Setup

Each player receives a complete set of cards in one colour, i.e. the values from 1 to 10 and one K card.
The players hold their cards in their hands.
Select a player to start, then play clockwise.


== Play

The game is about taking tricks and winning high value cards.
On your turn, either play a lower card than your predecessor, or pass.
You are allowed to pass tactically, even if you are able to play.
After passing, you may not play any more cards into the current trick.

The cards do not have to be consecutive as long as they are lower.
For example: if your predecessor played a 9, you can play an 8, or anything lower such as a 2 or even a 1.

It is quite possible that players will have more than one turn in one trick.
If, at the beginning of a player's turn, his own card still shows as the last card played, then obviously all other players have passed, and the player wins the trick.
He places the cards face down in front of him, and then plays the first card of the next trick.

Each player must be able to see all cards of the current trick.

When playing a card, the player calls out the current value of the trick.
The value of the trick is the sum of all its card values.
Each K card counts minus 10.
For example: after a 10 and an 8, the played plays a 4 and calls out '22'.

The K card may be played after any card, even after another K card.
It is always a bit lower than the previous card.
For example: a 4 may be followed by a K card, then by another K card, then by a 3.
If a trick is started with a K card it may be followed by any card.


== Game End

When a player plays his last card, the current trick is still played out.
Then the game ends.

Each player totals the values of the cards in his tricks and subtracts the values of the cards he has left in his hand.
The player with the highest score wins.

The easiest way of calculating your score is to add up all the cards from your hand and all your K cards.
Then neutralise these values with your other cards.
Then total your remaining cards to determine your score.

Play several games in a row.
Record the individual results on a note pad.
In the end the player with the highest total score wins.
