= Ohio
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

Un jeu de Reiner Knizia.

.Matériel
****
* 55 cartes: 1-10 & K à ♠, ♥, ♣, ♦, ✿
****

Ohio est un jeu de cartes passionnant, dans lequel les cartes ayant une valeur faible sont plus fortes que les cartes ayant une valeur élevée.
Tous les joueurs reçoivent exactement les mêmes cartes.
À tour de rôle, chacun joue une carte dont la valeur doit être inférieure à celle de la carte précédente.
Celui qui a joué la carte dont la valeur est la plus faible remporte le pli.
Le gagnant est celui qui à la fin de la partie totalise le plus de valeurs.


== Mise en place

Chaque joueur reçoit une série complète de cartes dans une couleur, c'est-à-dire des cartes allant de 1 à 10 plus la carte spéciale K.
Les joueurs tiennent leurs cartes en main dépliées en éventail.
On tire au sort pour savoir qui joue la première carte.
Ensuite, on joue dans le sens de des aiguilles d'une montre.


== Déroulement de la partie

Il s'agit d'obtenir les plis qui valent le plus de valeurs possible.
Lorsque c'est son tour, on peut soit jouer une carte dont la valeur est inférieure à celle de la carte précédente, soit passer son tour.
On a bien sûr le droit de passer son tour pour des raisons stratégiques, même si on aurait pu jouer une carte.
Une fois que l'on a passé, on ne peut plus participer à ce pli.

Les cartes n'ont pas besoin de se suivre les unes les autres, il faut juste que la valeur de chaque carte jouée soit inférieure à celle de la carte précédente.
Si un joueur joue un "9", le suivant peut jouer un "8", ou tout de suite un "2" ou même un "1".
Il est tout à fait possible que lors d'un même pli certains joueurs jouent plusieurs fois.

C'est seulement lorsque tous les autres joueurs ont passé que le joueur qui a joué la dernière carte remporte le pli.
Celui-ci place les cartes rapportées par ce pli devant lui, face cachée et joue la première carte du pli suivant.
Tous les joueurs doivent pouvoir bien voir les cartes du pli en cours.
Pour cela, celles-ci doivent être placées les unes à côté des autres sur la table.
Chaque joueur doit annoncer la valeur du pli après avoir joué sa carte.
La valeur du pli est égale au total des valeurs de toutes les cartes qui en font partie.
La carte spéciale K vaut moins 10 !

La carte K a le droit d'être jouée après n'importe quelle carte, même après une autre carte K.
Elle a toujours une valeur inférieure à celle de la carte précédente.
Par exemple : on peut jouer un 4, ensuite une carte K, ensuite encore une carte K et ensuite un 3.
Si un pli débute avec une carte K, n'importe quelle carte peut être jouée ensuite.


== Fin de la partie

Lorsqu'un joueur joue sa dernière carte, le pli en cours est encore entièrement joué.
La partie est ensuite terminée.

Chaque joueur additionne les valeurs des plis qu'il a gagnés et soustraits du total la valeur des cartes qu'il a encore en mains.
Chaque carte K vaut -10 points, qu'elle provienne d'un pli ou de sa main.
Le joueur qui totalise le plus de valeurs, gagne la partie.

La façon la plus sympathique de pratiquer ce jeu est de faire plusieurs parties à la suite.
À la fin de chaque partie, on note les valeurs que les joueurs ont obtenues.
Celui qui après un certain nombre de parties totalise le plus de valeurs, remporte la victoire.
