= Stick'em Classic
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 114 cards: 0-15, J, Q & K in ♠, ♥, ♣, ♦, ✿, ★
****

Each player is dealt cards.
They each select one of these cards to specify for themselves their “misery colour”.
The object of the game is to take as many tricks as possible, while avoiding cards of the “misery colour”.
Cards in the “misery colour” bring negative points, while the other colours bring positive points.
The player with most points wins.


== Game setup

The cards used in the game depend on the number of players.
The cards not listed are not used in the game.

* *3 players*: 0-8 in ♠, ♥, ♣, ♦ & ✿.
* *4 players*: 0-11 in ♠, ♥, ♣, ♦ & ✿.
* *5 players*: 0-14 in ♠, ♥, ♣, ♦ & ✿.
* *6 players*: 0-14 in ♠, ♥, ♣, ♦, ✿ & ★.
* *7 players*: 0-15, J & Q in ♠, ♥, ♣, ♦, ✿ & ★.
* *8 players*: 0-15, J, Q & K in ♠, ♥, ♣, ♦, ✿ & ★.

The cards are shuffled and dealt out to each player.
Each player will receive 15 cards (14 cards, if eight are playing).

NOTE: With seven players three cards remain un-dealt, and with eight players two cards remain.
These cards are shown to all players, and set aside.


=== Choosing your "Misery Colour"

Each player looks at his hand and chooses his “misery colour” for this hand.
He then selects a card of this colour from his hand and places it face down in front of him.
Once everyone has placed a card face-down, all players reveal them at the same time.
They then remain face up until the end of the round.
Thus, everyone knows every one else's misery colour.
It can happen that several players selected the same misery colour.

Each card in the misery colour that a player takes in tricks will score negative points according to the card's face value.
The misery begins with the selection of the misery colour, because the card used to declare a player's misery colour is counted against that player at the end of the round.

TIP: When selecting a misery colour, a player should not choose a colour in which he has only 1-3 cards, nor from a colour in which he has very many cards.
Also, it's better to choose a colour in which the cards he has have low numerical values, in order to avoid taking tricks with high cards in his misery colour.


== Game play

The starting player begins by playing a card to the centre of the table.
Next, each player must, in turn, play a card from his hand.
You need not follow suit.
Any card can be played.

The cards played into the centre of the table are the “trick”.
The colour of the first card played is the “lead colour”.
Every other colour played in that trick is a trump colour.
Every card in a trump colour is a trump card, except for the 0 card.

CAUTION: The 0 card is not a trump card.


=== Who wins a trick?

IMPORTANT: When playing with 7 or 8 players, the J card is valued 16, the Q card 17, and the K card 18.

* If only cards in the lead colour were played to the trick, the player who played the highest card wins the trick.
* If, other than cards of the lead colour, 0 cards were played, the player who played the highest card in the lead colour wins the trick.
A 0 card is not a trump card.
* If, other than cards of the lead colour, at least one trump card was played, the player who played the trump card with the highest card wins the trick.
A 0 card cannot win this trick.
* If more than one trump cards of the same highest numerical value were played, the player who played the first highest-valued trump card in the trick wins the trick.
* In a trick where the only cards played were 0 cards, then the player who led the first 0 card wins the trick.

The winner of the trick takes the cards and places them face-down in a pile in front of himself.
This player then begins the next trick by playing the first card.
The colour of this first card is the new lead colour.


=== End of the round, and scoring

After 14 tricks (13 tricks with eight players) the round ends.
Each player now has at least one card in his misery colour (the card used to declare that colour), and possibly other cards taken in tricks.
Each card in his misery colour counts as negative points according to the numerical value on the card.
Each card not in his misery colour counts as one positive point, independent of the value on the card.
To determine a player's score for the round, add the positive points and subtract the negative points.

IMPORTANT: When playing with 7 or 8 players, the J card is valued 16, the Q card 17, and the K card 18.

.Scoring
====
Axel used a ♥4 to declare his misery colour.
In his tricks he's taken a ♥2 and ♥5, as well as 14 cards in other colours.
For the 14 other cards Axel receives 14 points, and for the ♥ cards he receives stem:[4 + 2 + 5 = 11] negative points.
Thus, his score for the round is stem:[14 - 11 = 3] points.
====


=== The next round

After each player's score is tallied, the next round begins.
The player with the lowest score shuffles together the cards (including those set aside during the previous deal, if playing with 7 or 8 players), and deals the cards out (again setting aside the remaining cards).
If more than one player is on the lowest score then the player who scored lowest for the round is the dealer.
Each player selects a misery colour, which may or may not match his misery colour in the previous round.

The player left of the dealer begins the first trick, and play continues as already described.


== Ending the game

The game ends after five rounds.
The player who has the largest positive score is the winner.
If all players have negative points, then the player with the fewest negative points is the winner.


== Variants

=== “Reverse” Stick'em

The players select a personal “lucky colour” from the cards in their hand.
This means that each card in this colour that a player wins in tricks counts as positive points according to their numerical value.
Naturally, also the card chosen at the beginning to indicate this lucky colour counts positively.
However, now each card in other colours counts as one negative point, regardless of their numerical value.

IMPORTANT: The lowest trump card wins the trick, rather than the highest.
(A “0” card still does not win a trick.)
If several players play trump with the lowest value, the first player to play such a card wins the trick.

Otherwise, play with the same rules as in Stick'em “Classic”.


=== “Mild” Stick'em

Each misery card counts as five negative points, rather than negative face value.
This also applies to the 0 card in that colour.
Each card in other colours is still one positive point.

Otherwise, play with the same rules as in Stick'em “Classic”.


=== “Aggravated” Stick'em

Each player chooses two personal misery colours, and selects two cards from his hand.
Each card in the two misery colours brings negative points according to the numerical values on the cards, and cards in the other colours are worth one positive point each.

Therefore, with 3-7 players only 13 tricks are played, and with 8 players only 12 tricks.

Otherwise, play with the same rules as in Stick'em "Classic."


=== “Hazy” Stick'em

The card declaring a player's misery colour remains lying face down before each player.
It is not revealed until the end of the round.

Otherwise, play with the same rules as in Stick'em “Classic”.


=== “Delayed” Stick'em

The players select their misery colour not at the beginning of the round, but at the end, when counting the cards won in tricks.
Each player must select as his misery colour one that is represented in those cards won.
If a player has not collected any cards of a colour, then that player may not choose that colour to be his misery colour.

Players who did not take a trick receive 0 points.

In this variant 15 tricks are played (14 tricks with eight players).

Otherwise, play with the same rules as in Stick'em “Classic”.
