= Lost Cities: Flip & Write
:toc: preamble
:toclevels: 4
:icons: font

A game by Reiner Knizia, adapted from Roll & Write by Salomon BRYS.

.Components
****
* 60 numbered cards: 1-10 in ♠, ♥, ♣, ♦, ✿ & ★.
* 1 Monkey King first player card.
* As much link:Boards.pdf[game sheets] as there are players.
****

Hunt for points in the jungle!
One player flip four cards, chooses two as a result and writes it on their game sheet.
All other players also choose a result from the remaining cards and write it on their sheets.
Numbers must be noted in ascending order.
Those who land on the acceleration boxes or find gems may count themselves lucky.
If you cannot or do not want to write anything down, you can use your passes.
But not too often, as you want to make as much progress as possible in order to end with the most points.


== The game sheet

1. *Expeditions:* +
The game sheet shows six coloured expeditions running from the bottom to the top.
Each of the six expeditions has a different colour, corresponding to the six colours of the cards.
The expedition on the left is ♠, the one next to it ♥, then ♣, ♦, ✿ and ★.

2. *Gems and passes:* +
The right side of the game sheet shows a column with gems and next to it a column with card passing symbols.

3. *Score hexes:* +
At various places in the sheet, the small hexagons show the respective points for scoring:

a. on the left for the six expeditions (from -50 to 50)
b. on the right for the gems and card passing symbols (from -40 to 100 and 0)
c. a row with the bonus points (20 each) in the upper third of the sheet.

4. *Empty score hexes:* +
At the end of the game, write your points in the empty hexagons at the top of the game sheet.
Points are scored for the six expeditions, the gems column and the card passing column.
In the large empty hexagon at the top right, write your name and your overall score.

5. *Double point circle:* +
If you circle the ×2 value at the bottom of an expedition, the points of this expedition are doubled.


== Game Preparation

Each of you will receive one link:Boards.pdf[*game sheet*].

Place your game sheet in front of you so that all other players can easily see it during the game.

Give the first player card to a random player.
That player will be the first player to take their turn.

Shuffle the cards and create a draw deck of 24 random cards.
Discard the other cards without looking at them.

Each player should have a pen.


== Course of Play

The greatest adventurer takes the first turn (or the last person to go on a hike if unsure).

Play then continues in a clockwise direction.


=== Flip the cards and choose

When it’s your turn, flip four cards from the deck and place into the center.

*  Out of the four cards, pick one for its colour and one for its value and put them both in front of you.
You are *not allowed* to use the same card for both colour and value.

* The remaining two cards stay in the centre of the table and are available to all other players to use.
** Each of the other players may choose a combination of one colour and one value from the two cards in the centre of the table.
They *are allowed* to use the same card for both colour and value.
Leave the two cards in the middle.
Do not move them.
** Several players may choose the same combination.

Each player writes the selected colour & value combination on their game sheet — as described in <<Lead expeditions>>.


==== Refusing the draw

* The player who flipped the cards has the option to refuse the draw and not choose a card combination.
In this case, he has to discard one of the four cards (of his choosing).
The remaining three cards are left in the centre and are available to all other players.

* All other players also have the option to refuse the two or three cards and not choose a card combination.

Every player who refuses to write a result on their game sheet must mark their sheet as described in <<Refusing cards>>.


=== Lead expeditions

*The individual expeditions are tracked from bottom to top.*


==== ×2 symbol (double point)

If you combine a *10 value with the corresponding colour*, you can circle the "×2" symbol.
To use the ×2, it has to be *circled before* you start an expedition in that colour column.

You may start an expedition without circling the ×2 symbol, however, you are not allowed to circle it after the expedition has started.

If you start an expedition without using the ×2 symbol, cross it.

*If the ×2 symbol is circled, the expedition will be worth double points at the end.*


==== Expedition box

*If you are starting an expedition or if you are continuing an expedition*, write numbers into the nine boxes of the expedition one after the other (from bottom to top).
The smallest possible number is "1".

*The next number must be equal to or greater than the previous number.*

TIP: Of course, it's a good idea to start small and not to make too many big jumps.
This will ensure that you have as many numbers as possible to choose from later.


==== Acceleration box

If you write a number in a box with an arrow, you can accelerate any one of your expeditions.
To accelerate, enter the same number in the next box up on your chosen expedition.
(For example, if the expedition you chose to accelerate has a 2 as the highest number, enter a 2 in the box above that one.)
If the box you choose is also an acceleration box, you can accelerate again.
However, you may not use the acceleration to circle an ×2 symbol.

TIP: You can use an acceleration box to start a new expedition.
To do so, enter a 1 in the first box (and cross its ×2 symbol if it is not already circled).


==== Gem box

If you write a number in a box with a gem, you immediately circle a gem on the right side of your game sheet.
This is also done from bottom to top.
If you have already circled all available gems in the right-hand column then you have completed all your actions for that column.


==== Refusing cards

If you refuse the card draw, you must circle a card passing symbol on the right side of your game sheet.
This is also done from bottom to top.

If you have already circled all nine card passing symbols, you may still choose to refuse the draw without further effect.


==== Bonus bridges

If you have written a number in the seventh box of a column, or circled an gem or the card passing symbol in the seventh box, you have passed the corresponding bonus bridge and must announce this immediately.

You will receive *20 bonus points*, but only if you were the *first player to pass that bonus bridge*.
If more than one player passes this bridge in the same turn, they all receive 20 bonus points.

* Whoever receives the bonus may circle the "20" on the corresponding bridge.
* Those players who do not receive the bonus during the same turn must mark the corresponding bridge with a cross on their game sheet.

[TIP]
====
*Recommendation — play in sequence:*

In most cases, players will make their choice independently and may act simultaneously.
Sometimes, however, your own choice will depend on the choices made by others (for example, when receiving bonus points).
In this case you may request that the card combinations be chosen and written into the game sheet in clockwise direction.

Even if acting simultaneously, it is best to announce your entry out loud.

If you come across acceleration boxes, gem or bridges, you should also announce how you will proceed.
Then the next player in clockwise direction announces their choice, writes it into their game sheet, and so on.
This is the most exciting way to play, as everyone has an understanding of their opponents‘ turns
====


=== Continue play

Discard all four drawn cards.

If the draw deck is now empty, shuffle all cards, and create a new draw deck of 24 random cards.


== End of Game and Scoring

If a player circles the ninth (last) card passing symbol on the right side of their game sheet, they are "exhausted".
The player loses all points from this column.
However, the player continues to play the game.

Once you have circled your last card passing symbol, you will receive 0 points for this column.

*The game end triggers when at the end of a turn:*

* either all players are "exhausted"
* or all eight bridges have been passed.
The bridges may have been passed by different players.

Continue play until every player has had the same number of turn.

CAUTION: Once the game end has been triggered, players can pass (as before) but *do not circle card passing symbols* when doing so.

After the player to the right of the first player has taken their last turn, each player now tallies their score as follows:


=== Scoring expeditions

* For each of your six expeditions, take your point score on the left side of your game sheet.
This is determined by the highest number written into a box in that column.

* If three or fewer numbers are written in a column, the score is negative, after that the score is positive.

* If the *×2 symbol at the beginning of the expedition has been circled, then the score is doubled* (positive or negative).

* *If no entries are made at all in an expedition, 0 points are awarded for that column.*

* *Beware!*
*If you circled the ×2 symbol, without continuing the expedition, you will receive "-50" doubled, i.e. -100 points.*

* If you have circled the bonus bridge, add 20 points to the expedition.
*Attention: the bonus points for the bridges are not doubled.*

* The points achieved are written in the empty hexagons above the expeditions at the top of the game sheet.



=== Scoring gems and card passing symbols

* For your columns of gems and card passing symbols, take the points on the right side of your game sheet and write your score in the empty box above the respective columns at the top of the game sheet.

* A completed column with nine circled gems is worth 100 points.

* A completed column with nine circled card passing symbols renders you "exhausted" and earns 0 points.
However, eight circled card passing symbols earn 70 points.

* Should you be "exhausted", the 20 bonus points in the card passing column will still count.


=== Total points scored + winner

Each player writes their *points in the hexes at the top* of their game sheet.
The resulting sum is written in the large hex at the top right of the sheet together with the player's name.
The player with the highest score wins.
If there are multiple players with the most points, they all win.

