= Hi MiLo!
:toc: preamble
:toclevels: 4
:icons: font

A game by John Burton, adapted to Super-Set-Deck by Salomon BRYS.

.Components
****
* 72 numbered cards: 1-18 in ♠, ♥, ♣ & ♦.
* 14 Hi MiLo! cards:
** 12 coloured: J, Q & K in ♠, ♥, ♣ & ♦.
** 2 neutral: J & K in ★.
* 2 bet cards: 1 butterfly & 1 dragon.
****


Hi MiLo! is cooperative trick-taking game for 3 to 5 players where the rules for playing cards and winning tricks changes for each trick, based on the unique Hi MiLo! Deck.
Your team strategy will never be the same twice as the Hi MiLo! Deck is shuffled between rounds, creating a whole new set of rules for every game!
After seeing their cards, players bid to take the highest, middle, and lowest number of tricks in a round.
Without discussing their cards, players work cooperatively to take tricks which would allow each player to make their bid.
If all players successfully make their bids, the team wins together!


== Setup

* *3 players*: Play with cards 1 to 12 (remove cards numbered 13 to 18).
* *4 players*: Play with cards 1 to 15 (remove cards numbered 16 to 18).
* *5 players*: Use all the numbered cards.

Shuffle the numbered cards and deal 14 cards to each player.
The remaining un-dealt cards are discarded face down for the round.

Players keep their cards hidden from each other.

Shuffle the Hi MiLo! Cards together, fan out the cards face up on the table away from the main play area so all colours and ranks are visible.
There is one Hi MiLo! card for each trick in a round.
The top card (the one not covered by other cards) is known as the "Win Card" for the trick.
These cards determine the rules for each trick played in a round.


== Play

[[tricks]]
=== Tricks

Hi Milo! is a trick-taking game like Hearts, Spades, or Bridge, and follows many of the same rules as those classic games.
Each player places one card face up on the table and one wins the trick based on the value of the cards.
However, Hi Milo! is unique in that the Hi Milo! Deck determines the rules for which cards you can play and which cards will win any trick.
The Win Card for the trick is collected by the winner of the trick, and the next Win Card determines the rules for the next trick.

The Win Card determines the rules for a trick in two ways.

First, players must play a card of the same colour as the Win Card if possible.
If the Win Card is neutral (★), players can play any cards and only the number value determines the winner.

Second, the rank of the Win Card determines who wins the trick:

* If the Win Card is ranked *K* ("Hi"), the highest value card wins the trick.
* If it is *J* ("Lo"), the lowest value card wins the trick.
* If it is *Q* ("Mi"), the player who played the card in the middle of the highest and lowest cards wins the trick.
** *3 players*: the player who played the *middle card* which has 1 card above and 1 card below wins the trick.
** *4 players*:
*** ♠ & ♣: the player who played the *high middle card* which has 1 card above and 2 cards below wins the trick.
*** ♥ & ♦: the player who played the *low middle card* which has 2 cards above and 1 card below wins the trick.
** *5 players*: the player who played the *exact middle card* which has 2 cards above and 2 cards below wins the trick.

Players are not allowed to discuss the cards in their hands in any way with the other players.


=== Bidding

At the start of a round, players look at their cards and silently estimate how many tricks they think they will take.
Specifically, they are trying to guess if they will take the highest number of tricks of any player, the lowest number of tricks of any player, or take a middle number of tricks.
Players can talk amongst themselves to decide who should bid at what level, but they cannot describe the cards in their hands.

Players should stick to phrases like "I think I can take middle, or maybe high".
At the end of bidding, only one player should be the "High" bidder, only one should be the "Low" bidder, and the rest are "Middle" bidders.

* The "High" bidder places the dragon card in front of them.
* The "Low" bidder places the Butterfly card in front of them.


=== Passing Cards

Starting with the player who bid High, each player passes 3 cards to the player on their left, not letting the other players see the cards.
Players can look at the cards passed to them before passing cards themselves.

After the last player passes 3 cards to the High bidder, the round is ready to begin.


=== Playing Cards

For the first trick of a round, the player to the left of the dealer plays one card face up to the table.
In clockwise order the next players each play one card to the table face up.
The only rule for playing cards is that players must play a card of the same colour as the Win Card if possible.
After all cards are played, the winner of the trick is determined (see below).
The winner of the trick collects the Win Card and discards the cards played to the trick.
The winner of the trick plays the first card in the next trick.

.Determining the Trick Winner
****
Cards are ranked from low to high 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18.

Cards are further ranked as follows:

1. Cards of the same colour as the Win Card always rank higher than cards of other colours ("Off Colour Cards").
2. Off Colour Cards are ranked only by numerical value.
3. If more than one Off Colour Cards share the same numerical value, the earlier one of these cards played ranks higher.

Of the cards played, one is ranked as the Highest, one is ranked the Lowest, and the rest rank in the middle by the rules above.
If the Win Card is "Hi" (K), the highest value card wins the trick.
If it is a "Lo" (J), the lowest value card wins the trick.
If it is a "Mi" (Q), one of the middle value cards wins the trick (see <<tricks>>).
****


== Scoring the Round

After the last trick is played, players count how many tricks they have won and rank themselves with the player who won the most tricks as the "High" player, the player who won the least number of tricks as the "Low" player, and the rest rank as "Middle" players.
Compare this ranking with the bids made by each player at the start of the round.

If all players' rank match their bids, the team wins!

If not, the team loses.
If there is a tie between two or more players for either the highest tricks won, or the lowest tricks won, then the players lose.

To win, players pick a set number of games (such as best of 5) and attempt to win more than they lose.


== Variant: make the game harder

When creating the Hi MiLo! line of cards, only show a specified number of cards, and place the remaining in a face-down pile.
Each time a trick is won by a player and the Win Card is removed from one end of the line, if there are remaining face-down Hi Milo! cards, place one from the pile face up at the other end of the line (under all other face-up Hi Milo! cards, but still showing its colour and rank).

* Medium: show 7 cards.
* Difficult: show 5 cards.
* Hardcore: show 3 cards.
