= The Fox in the Forest
:toc: preamble
:toclevels: 4
:icons: font

A game by Joshua Buergel.

.Components
****
* 33 game cards: 1-11 in ♠, ♥ & ♣.
****

The Fox in the Forest is a trick-taking game for two players, each playing cards to win tricks against the other over multiple rounds.
Players score points during a round by winning tricks containing specific cards and at the end of a round based on the number of total tricks they won.
The player with the most points at the end of the game is the winner.


== Setup

Each game consists of multiple rounds.
In each round, one player will be the dealer.
(For the first round, randomly select the dealer. For each round after that, alternate which player is the dealer.)
At  the beginning of a round, the dealer for the round completes the following steps:

1. Shuffle the *33 game cards*.
2. Deal both players a *hand* of 13 cards.
   (Each player may look at their own hand but should keep their hand hidden from the other player.)
3. Set aside the remaining 7 cards face down to make a *draw deck*.
4. Take the top card of the draw deck and place it face up next to the draw deck.
   This card is known as the *decree card*.
   (The suit of this card will be important during the round.)


== Gameplay

=== Round Overview

Each round consists of a series of 13 turns for each player, called *tricks*.
Every trick, both players will play one card from their hand face up into the middle: one player will *lead* (that is, play the first card of the trick), and the other player will then *follow* (that is, play the second card of the trick).
Based on the two cards that are played, one player will be said to *win the trick*.


=== Trick Details

*Leading:*
The non-dealer leads on the first trick of a round.
After that (unless specified otherwise), the winner of one trick will lead the following trick.
The leader can choose to play any card from their hand, without restriction.
The suit of that card is known as the *lead suit* for the trick.

*Following:*
After one player leads, the other player now must play a card that (if possible) matches the lead suit; that card can be (unless specified otherwise) of any rank in that suit.
If the follower does not have a card in the lead suit, they may play any card without restriction.

*Determining the Trick Winner:*
After both cards have been played (and any abilities activated; see Abilities), players determine the winner of the trick.
Typically, the card with the highest rank in the lead suit wins the trick.
However, the suit of the decree card (known as the *trump suit*) is considered higher than the lead suit:

- If either card in the trick is in the trump suit, the player who played the card in the trump suit with the highest rank wins the trick.
- If neither card in the trick is in the trump suit, the player who played the card in the lead suit with the highest rank wins the trick.

The winner of the trick takes the two cards and keeps them face down near their side of the table.
The number of tricks won by each player is public information, visible to both players during the round.
However, no player may look at the faces of cards in previously won tricks.

The winner of a trick leads the next trick (unless otherwise specified).
Continue to play tricks until all 13 tricks have been won.


=== Abilities

All the cards of odd rank (1, 3, 5, 7, 9, and 11) have special abilities printed on them, which activate when the card is played.
They may change what your opponent can play, how the winner of the trick is determined, or who leads the next trick; they may let you take a special action when you play the card; and they may give points to the winner of the trick.

****
- *1*: If you play this and lose the trick, you lead the next trick.
- *3*: When you play this, you may exchange the decree card with a card from your hand.
- *5*: When you play this, draw one card, then return any one card to the bottom of the deck face down.
- *7*: Every 7 won is worth 1 point.
- *9*: When determining the winner of a trick with only one 9, treat that 9 as if it were the trump suit.
- *11*: When you lead this, if your opponent has this suit, they must play either the ace of this suit or their highest card of this suit.
****

(See the <<apendix>> for any additional help with these abilities.)


=== End-of-Round Scoring

After all 13 tricks have been played, count how many tricks each player has won.
Players may win points at the end of the round, based on the number of tricks they won.
(See the chart below.)

You want to win more tricks than your opponent, but not too many.

[options="header,autowidth",cols="^.^,^.^,^.^"]
|===
| Tricks | Points | Description
| 0-3    | 6      | Humble
| 4      | 1   .3+| Defeated
| 5      | 2
| 6      | 3
| 7-9    | 6      | Victorious
| 10-13  | 1      | Greedy
|===

(If you get too greedy, you will be brought down like the villain in so many fairy tales.)

After the end-of-round scoring, if either player has at least 21 points, then the game is over.
Otherwise, play another round (with the dealer of the next round being the player who did not deal the current round).


== End of game

Play complete rounds until either player has at least 21 points.
The player with the most points wins!
If there is a tie, the player who won the most points during the last round wins.

*Variable game length:*
For a shorter or longer game, you may agree to end the game at a different number of points:

- For a shorter game, we recommend playing complete rounds until either player has at least 16 points.
- For a longer game, we like playing complete rounds until either player has at least 35 points.


[[apendix]]
== Appendix: common questions

- *When do the abilities on the 3 and 5 occur?* +
  Each of these two abilities takes place immediately when the card is played, before another card is played or the winner of the trick is determined.
+
NOTE: If the person playing a 3 changes the decree card, the trump suit may also change.
      The new trump suit is used to determine the winner of the current trick.

- *If my opponent leads a 9, do I have to follow the 9’s suit or the trump suit?* +
  You must follow the 9’s suit if you can.
  A non-trump 9 is not treated as if it were in the trump suit until after both cards in the trick have been played following the normal rules.

- *If my opponent leads a trump card and I have a trump card, can I play a non-trump 9?* +
  No. A non-trump 9 is not treated as if it were in the trump suit until after both cards in the trick have been played following the normal rules.
  If you can follow suit with a trump card, you cannot play a non-trump 9.

- *Who wins a trick with two 9 cards in it?* +
  The special ability on the 9 only applies when the trick contains one 9.
  If the 9 of the trump suit was played, it would win; otherwise, the 9 of the lead suit would win.

- *Who leads the next trick after a trick with two 1 cards in it?* +
  If both players play a 1, the player who loses the trick would lead the next trick.
