= Okey Dokey
:toc: preamble
:toclevels: 4
:icons: font

A game by Hisashi Hayashi.

.Components
****
* 40 Number cards: 1-8 in ♠, ♥, ♣, ♦ & ✿.
* 10 Reset cards: 2 Ks in ♠, ♥, ♣, ♦ & ✿.
* 3 Phoenixes.
****

All of you have gathered to organize a spectacular music festival.
Vocals, guitars, drums, pianos and bass from all over the land come together to play their part in this special event.
Many bands have gathered, and each performer has their part to play in creating a successful music festival!


== Object of the Game

Okey Dokey is a cooperative game and players are not competing but striving together for the common goal of successfully staging the festival.
Players play cards one by one in accordance with the rules to a 5 by 10 grid to create a colourful music festival.


== Goal of the Game (in detail)

The goal of the game is to be able to play all 50 Number and Reset (K) cards to a grid of 5 rows by 10 columns

[options="autowidth", frame=none, grid=none, cols="^,^,^,^,^,^,^,^,^,^,^"]
|===
h| ♠ | 2 | K | 1 | 3 | 7 | 8 | K | 4 | 5 | 6
h| ♥ | K | 2 | 3 | 4 | 5 | 6 | 7 | 8 | K | 1
h| ♣ | 1 | 2 | 5 | K | 3 | 4 | 6 | 7 | 8 | K
h| ♦ | 2 | 6 | K | 7 | 8 | K | 1 | 3 | 4 | 5
h| ✿ | 1 | 3 | 4 | 6 | K | 2 | 5 | K | 7 | 8
|===


== Setup of the Game

1. First, determine the level of difficulty of the game.
The level of difficulty determines the number of Phoenix cards to be used in the game.
+
[%autowidth]
|===
| Difficulty Level | Number of Phoenix cards

| Amateur | 3
| Standard | 2
| Professional | 1
| Maestro | 0
|===

2. Shuffle the corresponding number of Phoenix cards plus all the Number cards well into a face down deck.
Return the unused Phoenix cards to the box, they will not be used in the game.
Then, distribute the Number cards (with the Phoenix cards mixed in, but not the Reset cards) in accordance with the number of players.
The number of cards each player has indicated by the table below:
+
[%autowidth]
|===
| Player count | Starting hand size

| 1 player  | 10 cards
| 2 players | 7 cards
| 3 players | 6 cards
| 4 players | 5 cards
| 5 players | 4 cards
|===
+
The remaining cards are placed in a Number card deck in reach of all players.

3. Set up the Reset cards by placing 5 piles of 2 K cards each face-up in 5 rows:
+
[%autowidth]
|===
| ♠K
| ♥K
| ♣K
| ♦K
| ✿K
|===

4. Decide on a Start player by discussing amongst all players.
Players look at their own hands and decide who should begin.
When the game begins, play will proceed in turns clockwise from the Start player.
You are now ready to begin!


== Flow of the Game

The game will proceed in turns until all 50 cards are placed in the grid.
The game takes place in turns clockwise from the Start player.

CAUTION: *Exception*: In a 5 player game, when the fifth column of each row is placed, that player immediately takes another turn.

On a player’s turn, they carry out 1 of the following 2 actions:

a. Play a Number card.
b. Place a Reset card.

If, during a player's turn, they are not able to carry out an action (either (a) or (b)), the game ends immediately and the players have lost the game.


=== a. Play a Number card

Play a Number card to the grid.
A Phoenix card is also possible in place of a Number card.
The card placement rules (to follow) must be obeyed.
After playing a Number card, the player draws a card from the Number card deck to their hand if available.


=== b. Place a Reset card

Choose one colour, and place a Reset (K) card from that row into the grid.
This action cannot be taken if there are no Reset cards left of that colour.
Reset placement rules (to follow) have to be obeyed.
Then, if there is at least one card remaining in the deck, the player chooses 0 to 2 cards from their hand to discard face down to the bottom of the deck, and draws the same number of cards that they discarded from the top of the deck.


=== Drawing cards

Once the deck runs out, Players will be unable to draw any more cards.

In addition, when placing a Phoenix card, players may discard a Number card of the colour of the row where the Phoenix card was placed.
Place the discarded card under the Phoenix card that was just placed.
Only one card may be discarded per Phoenix card.

If a player runs out of cards in their hand, their turn will be skipped for the rest of the game.


=== Card Placement Rules

==== Column Placement Rules

Cards must be placed in the current column.
Only when columns are complete can a new column be created.
(e.g. Only after placing 5 cards in column 1 can you place a card in column 2).

* *OK example*: The column has 5 cards, so the ♥4 *can* be placed.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠1 | _
| ♥3 | <- ♥4
| ♣2 | _
| ♦K | _
| ✿4 | _
|===

* .*Error example*: The column only has 3 cards, so the ♥4 *cannot* be placed.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| _  | _
| ♥3 | <- ♥4
| ♣2 | _
| ♦K | _
| _  | _
|===


==== Colour Placement Rules

Each row must contain the same colour of Number cards.
In addition, there is exactly only one row for each colour.
(For example, even if a Reset card is placed in the first column of the first row, all subsequent cards still have to be ♠).

* *OK example*: Same colour, so the ♥4 *can* be placed.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠2 | _
| ♥3 | <- ♥4
| ♣K | _
| ♦1 | _
| ✿4 | _
|===

* *Error example*: Different colour, so the ♥4 *cannot* be placed.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠2 | <- ♥4
| ♥3 | _
| ♣K | _
| ♦1 | _
| ✿4 | _
|===


==== Number Placement Rules

The number of the card played must be equal to or greater than the number of the card to the right of it.
You may play a Reset (K) card regardless of the number of the previous card.
If a Reset card is placed, it is equivalent to resetting the number to zero (i.e. any card number may be subsequently played).

* *Example*.
+
[options="autowidth", frame=none, grid=none, cols="^,^,^"]
|===
| ... | ♠6 | <- Here, a ♠7, ♠8, Phoenix or ♠K may be played.
| ... | P  | <- Here, any ♥ number card, Phoenix or ♥K may be played.
|===


==== Reset Placement Rules

In every column of 5 cards, there must be exactly 4 Number cards and 1 Reset (K) card.
At the end of the game, there should be exactly two Reset cards per row.

* *OK example*: There is exactly 1 Reset (K) in this column.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠2
| ♥3
| ♣4
| ♦1
| ✿K
|===

* *Error example*: There are 2 or more Reset cards in this column.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠3
| ♥7
| ♣K
| ♦K
| ✿2
|===

* *Error example*: There are no Reset cards in this column.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠3
| ♥4
| ♣8
| ♦1
| ✿2
|===


==== Phoenix Placement Rules

Phoenix cards may be placed instead of any Number card.
When a Phoenix card is played, the value of the Phoenix card is the same as the card to its left.
If the card to the left is a Reset (K) card, then the value of the Phoenix is zero.

* *Example*.
+
[options="autowidth", frame=none, grid=none, cols="^,^"]
|===
| ♠6 | P <- Treat this Phoenix as a ♠6.
| ♥2 |
| An | P <- Treat this Phoenix as a ♣0.
| ♦3 |
| ✿1 |
|===


== End of game

When all the 50 cards have been placed in the grid, and all 10 columns have been filled, the players have won the game.
If this cannot be accomplished, then the players have lost the game.


== Rules regarding player discussion

No player may show their hand to another player.
Players may not say or give hints about the number values of their hand.
However, players may reveal how many cards they have in a colour.
They may also suggest a colour that they would like to be played.


== Hints

* For every column, it can be useful to discuss who places which colour, and who will play the Reset card.
* Number 1 cards can only be placed in the first column or after a Reset (K) card, so try to play them as soon as possible.
* Besides the 10th column, try to avoid placing number 8 twice in the same column.
