= Lost Cities
:toc: preamble
:toclevels: 4
:icons: font

A game by Reiner Knizia.

.Components
****
* Base game:
** 5 A cards: ♠, ♥, ♣, ♦, ★.
** 60 Playing cards:
*** 45 numbered Expedition cards: 2-10 in ♠, ♥, ♣, ♦ & ★.
*** 15 Wager cards (3 Ks of each color).
* Advanced game:
** 1 additional A card (✿).
** 12 additional Playing cards:
*** 9 Expedition cards: 2-10 in ✿.
*** 3 Wager cards (Ks of ✿).
****

*The Duel of the Explorers*

Place your cards to form expedition routes that lead you to remote and mysterious corners of the Earth:
the Himalayan mountains, the Central American rainforest, the Egyptian desert, a mysterious volcano, and the bottom of the sea.
And if you are particularly daring, you can also bet on the success of an expedition with wager cards.
But beware: this can backfire.
If after three games you have the highest overall score, you win.

NOTE: The game rules are very simple.
But don't get the wrong  impression.
There is much more to discover in Lost Cities than it might seem at first glance!


[[preparation]]
== Preparation

Place the *5 A cards* (♠, ♥, ♣, ♦, ★) in a line in the middle of the table between the two players.
They are the five spaces for discard piles.

Place the ✿ A card and the 12 ✿ playing cards (9 expedition cards & 3 wager cards) in the box.
They are not needed for the base game.

Shuffle the 60 playing cards.
Give *eight cards* face down to each player.
These are your *cards*.
Organize the remaining cards into a *draw pile* and place them face down next to the middle line.

Have a pen and paper, or smartphone, ready to tally your scores.


== Object of the Game

Each player’s goal is to form expedition routes that — after subtracting the expedition costs — earn the player as many discovery points as possible.
You set up the expeditions by forming  a separate column of cards for each color.
The numeric values within a column of cards must increase from card to card.
You can place wager cards at the beginning of each column to multiply a column’s value.
At the end of the game, the cards in each player’s columns are scored.


== Sequence of Play

The oldest player begins. Afterward, the players alternate turns.
Each player only places cards on his or her side of the game board.

During your turn, you must first play *one of the cards from your hand*.
Only afterward are you allowed to *draw one new card*.


=== 1. Play a card

Choose a card from your hand. You have two options:

.Option 1: Place a card in one of your own expedition columns.
****
You can use this card to *start a new expedition* or *expand an existing expedition*.
To do this, place the card face up on your side of the game board, below the space for the discard pile of the corresponding color.

You may only place additional cards at the end of a column.
Place the cards in a column overlapping each other in such a way that the numbers of all the cards are clearly visible.

IMPORTANT: Each new card you place in a column must have a *higher value* than the most recent card you have placed in this column.

A *wager card* may only be placed at the beginning of a column.
You may place multiple wager cards on an expedition.
However, as soon as you have placed a number card on an expedition you can no longer place any wager cards of this expedition’s color.
****

*or*

.Option 2: Discard a card.
****
If you don’t want to (or can’t) place a card on an expedition, you must place a card from your hand face up oon the space for the discard pile of the corresponding color.
In this manner, five discard piles are formed during game play, one for each color.
The cards should be placed on the piles so that only the top card is visible.
****


=== 2. Draw a card

Draw a new card into your hand.
You have two options: Take the top card from the draw pile *OR* take the top card from one of the five discard piles (if there is a card there).

IMPORTANT: You are not allowed to draw the same card you have just discarded.

Once you have drawn a card, your turn ends.


== End of the Game and Scoring

The game ends *as soon as* a player draws the last card from the draw pile.

NOTE: Near the game’s end, the players may agree to fan out the face-down draw pile a little and count the remaining cards to enable the players to estimate the number of turns before the game ends.

When the game ends, each player’s expeditions are scored. +
To do this, tally up the values of all the cards in each expedition (each  column of cards).
From each column’s sum, subtract 20 points.
This is the expedition cost for that column.

IMPORTANT: If you have not placed *any cards* of a certain color, *no expedition costs* are incurred for this color.

*After deducting the expedition cost*, if one, two, or three wager cards were placed at the beginning of a column, multiply the result by two, three, or four, respectively.

Hence, a column can earn you positive or negative points.

If you  haven’t placed any cards of a certain color, you don’t earn any points for this color.
Furthermore, each column consisting of *at least eight cards* earns its owner a bonus of 20 points.

IMPORTANT: This bonus is *not* multiplied by wager cards!

Write down the number of points obtained by each player.
Then  start a new game as described in the <<preparation>> section.
This time, the player who has the most points goes first.

If after three games you have the highest overall score, you win!


== Variant: long game with six expeditions

The long game is played the same as previously described but with the following changes:
During game preparation, place the ✿ A card at the end of the line to form a *sixth expedition space*.
Then shuffle all *72 playing cards*, including the 12 ✿ playing cards.


== Scoring example

A player has placed cards as shown here.

[options="autowidth",cols=">h,^,^,^,^,^",role="big-table"]
|===
| | ♠ | ♥ | ♣ | ♦ | ★

| Cards
|
5 +
8 +
10
|
Q
|
|
J +
3 +
5 +
7
|
K +
J +
2 +
3 +
5 +
7 +
8 +
10

| Sum | 23 | 0 | 0 | 15 | 35
| Expedition cost | -20 | -20 | | -20 | -20
| Subtotal | 3 | -20 | 0 | -5 | 15
| Wager | | × 2 | | × 2 | × 3
| Total | *3* | *-40* | *0* | *-10* | *45*
| ≥ 8 cards bonus | | | | | *20*
|===

*Explanation of the ♥ Column:* +
The wager card doubles the value of the column.
Since no other cards have been played, only the expedition costs are incurred, which are doubled.

The player has earned 18 points: stem:[3 - 40 - 10 + 45 + 20 = 18]

TIP: As you can see in the example, it is better not to start an expedition in the first place if you can’t bring it to a satisfactory conclusion.
Also, you should only play wager cards if you have enough cards for an expedition and there is still time to place those cards!
