= Hanamikoji
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 7 Geisha numbered cards: ⎈2, ✿2, ♦2, ♣3, ♥3, ♠4 & ★5
* 21 Item cards:
** ⎈: K & Q
** ✿: K & Q
** ♦: K & Q
** ♣: K, Q & J
** ♥: K, Q & J
** ♠: K, Q, J & S
** ★: K, Q, J, S & C
* 8 Action cards: 2 Wolves, 2 Snakes, 2 Phoenixes & 2 Dragons
****

Welcome to the most well-known geisha street in the old capital, Hanamikoji.
Geisha, the graceful women elegantly mastering in art, music, dance, and a variety of artistic performances after years of training, are greatly respected and adored.
Geisha may be translated to “artist” and they dance, sing and entertain everyone.

In Hanamikoji, two players compete to earn the favors of the seven geisha masters by collecting the performance items with which they excel.
With careful speculation and sometimes a few bold moves, you may earn the essential items by giving away the less critical ones.
Can you outsmart your opponent and win the most favors of the geisha?


== Aim of the Game

In the game of Hanamikoji, the aim is to win 4 Geisha or 11 (or more) Charm Points.

You and your opponent take turns to perform actions to get different kinds of Item Cards.
For each Geisha, if you have more Item Cards of the corresponding type than your opponent, then you win the Geisha’s favor.

The game will continue until either player has reached the winning goal in the Scoring phase.


== Game Setup

1. Place 7 Geisha numbered Cards in a row, in the following order from left to right, between players: ⎈, ✿, ♦, ♣, ♥, ♠, ★.
2. Stack the Item Cards face-down into a pile and place them aside.
3. Each player takes 4 Action Cards (1 Wolf, 1 Snake, 1 Phoenix & 1 Dragon), and places them face up in front of himself.
4. The younger player is the starting player.


== Sequence of Play

The game is played for *one or several rounds*.
Each round consists of 3 phases in the given order:

* Phase 1: Deal
* Phase 2: Action
* Phase 3: Scoring and Update

If any player reaches the winning goal in the Scoring phase, the game ends immediately.
If neither player reaches the winning goal, the game proceeds to the next round.
The game will continue until either player wins.


=== Phase 1: Deal

The starting player shuffles all 21 Item Cards into a face-down pile, and randomly removes 1 card from the game and put it back to the game box *unseen*.
This card will not be used this round.
Nether player is unable to check it.

Deal each player 6 Item Cards as a hand.
Hand information is hidden.

Stack the remaining Item Cards face-down as the “Item deck” and put them next to the row of Geisha Cards.


=== Phase 2: Action

Beginning with the starting player, players alternate to *take one turn (Player A → Player B → Player A → Player B → and so forth)* until both players have taken *4 turns*.

In your turn, you must draw a card from the Item deck, and then *perform an action*.
*There is no fixed action order*.

When you perform an action, you choose 1 of your *unused* Action Card and perform the corresponding action.
After resolving the action, turn the card 90 degrees on its side to indicate it has been used.
You can’t choose a used action card (each of the player’s action card will only be used once during the round).

There are 4 actions in Hanamikoji:


==== Wolf

Choose 1 card from your hand, and place it *face-down* under the Wolf.
This card will be revealed in the Scoring phase and *be scored*.

You can check this card at any time.


==== Snake

Choose 2 cards from your hand, and place them *face-down* under the Snake.
These cards will *not be scored* in this round.

You can check these cards at any time.


==== Phoenix

Choose 3 cards from your hand, and place them *face-up* in front of yourself.

Your opponent chooses 1 card from them, and places this card on his side next to the *corresponding Geisha*.
Then, place the 2 remaining cards on your side next to the corresponding Geishas.
These cards will *be scored*.


==== Dragon

Choose 4 cards from your hand, and place them *face-up* in front of yourself.
You divide them into two sets, each containing 2 cards.

Your opponent chooses 1 set, and places these 2 cards on his side next to the *corresponding Geishas*.
Then, place the 2 remaining cards on your side next to the corresponding Geishas.
These cards will *be scored*.


=== Phase 3: Scoring and Update

After both players have performed 4 actions, the game proceeds to Phase 3.

Both players reveal the card under their Wolf, and place this card on their side next to the corresponding Geisha.
Then, compare the number of Item Cards on both sides of each Geisha:

* One side is more than the other: The side with more Item Cards wins this Geisha.
Move the corresponding Geisha card a few centimeters towards to winning player's side.
* Two sides are draw or no cards: Don’t move the Geisha card.

After scoring, both players calculate the number of Geisha they win and the sum of their Charm Points.
If any player reaches the winning goal, the game ends immediately (See: <<end>>).

If neither players reach the winning goal, proceed to the Update:

* Pick up ALL the Item Cards on the table and in the box, stack them face-down into a pile and place them aside.
* Geisha cards remain in place.
+
NOTE: Don’t move them back to the center of the table.
* Both players turn their Action Card back straight.
* The second player becomes the new starting player.
* The next round is ready to begin.


[[end]]
== End of the Game

If any player wins 4 Geisha or 11 (or more) Charm Points, the game ends immediately.

If only one player reaches the winning goal, he is the winner.

If one player wins 4 Geisha and the other wins 11 (or more) Charm Points, the latter is the winner.

.Victory
====
[options="autowidth",frame=none,grid=none]
|====
| ⎈2 |    |    | ♣3 | ♥3 |    |
|    |    | ♦2 |    |    |    |
|    | ✿2 |    |    |    | ♠4 | ★5
|====

Top player wins 3 Geisha, with a total of 8 Charm Points. +
Bottom player wins 3 Geisha, with a total of 11 Charm Points.

Since the bottom player reaches the winning goal, the game ends immediately.
Bottom player is the winner.
====
