= Odin
:toc: preamble
:toclevels: 4
:icons: font

[.ssd-components]
.Components
****
* 54 cards: 1-9 in ♠, ♥, ♣, ♦, ★, ✿.
****

Be the first to discard all the cards from your hand and have the fewest points at the end of the game.


== Setup

1. Shuffle all the cards.
2. Deal 9 cards face down to each player.
   This is your hand.
   Feel free to look at your hand, but don’t let anyone else see!

Choose a first player at random.
You will then take turns in clockwise order.


== How to play

The game is played over several hands.
Each hand is divided into rounds.

At the start of a round, if you are the first player, play 1 of your cards face up in the middle of the table.

Each player then takes turns to either: +
1. Play 1 or more cards +
or +
2. Pass


=== 1. Play 1 or more cards

The value of the cards you play must be greater than the value of those already in the middle of the table.

.Higher card
====
If the value in the middle of the table is 3, you must play a value of 4 or higher.
====

You can play either the same number of cards as already in the middle of the table, or 1 card more.

.More cards
====
If there is already a set of 2 cards, you can play a set of 2 cards or a set of 3 cards.
However, you cannot play a set of 4 cards. You also cannot play 1 card on its own.
====

If you want to play multiple cards, they must be of the same number or the same colour.

When you play multiple cards, calculate their value by using each card number as a digit to create the highest number possible.

.Set value
====
If you play 2 and 8 of the same colour, the value of the set is 82 (not 28).

If you play 2, 4, and 9 – also of the same colour – the value of the set is 942.
====

Once you have played 1 or more cards, you must pick up 1 card from the middle of the table.
You cannot pick up a card you have just played.
Therefore:

- If there is only 1 card, you must pick it up.
- If there is a set of cards, choose 1 card and discard the rest of the set.


=== 2. Pass

If you pass, do not play any cards.
The player on your left now takes their turn.

NOTE: If you pass this turn, you can play as normal on your next turn.

If all but 1 player pass, the round ends.
Keep the cards you have in your hand.
If there are any cards in the middle of the table, discard them.
If you were the last player to play a card, you start the new round.


== End of a hand

A hand can end in 2 ways:

1. If you start a new round and all the cards in your hand are of the same number or same colour, you are allowed to play them all.
The hand is now over.
If you cannot do this, play 1 card as normal.

2. If, at any point in the game, you play 1 or more cards and your hand is now empty, do not take a card from the middle of the table.
The hand is now over.

At the end of a hand, you receive 1 point for each card left in your hand.
Keep note of your points.

To start a new hand, collect all the cards and shuffle them.
Deal 9 cards to each player.
If you were the first player for the previous hand, the player to your left starts the new hand by playing 1 card.


== End of the game

If you are playing the game for the first time, we recommend playing to 15 points.
Therefore, once a player has 15 points or more, the game ends.
The player with the fewest points wins!
In case of a tie, those players share the victory.

After your first game, you can choose the number of points you want to play to.
For long games, you could play to 20.
For short games, to 10.
For super short games, just play 1 hand!
