= Odin
:toc: preamble
:toclevels: 4
:toc-title: Sommaire
:icons: font

Un jeu de Gary Kim, Hope S. Hwang, & Yohan Goh.

.Matériel
****
* 54 cartes: 1-9 à ♠, ♥, ♣, ♦, ✿.
****

Soyez le premier à vous défausser de toutes les cartes de votre main et à cumuler le moins de points à la fin de la partie.


== Mise en place

1. Mélangez les cartes.

2. Distribuez-en 9, face cachée, à chaque joueur et joueuse.
   Prenez connaissance des cartes de votre main sans les montrer aux autres.

Choisissez aléatoirement un premier joueur ou joueuse.
Vous jouerez ensuite à tour de rôle et dans le sens des aiguilles d’une montre.


== Déroulement du jeu

Le jeu se déroule en plusieurs manches.
Celles-ci se divisent en tours.

NOTE: nous faisons une différence entre « tour » et « tour de jeu ».
Un tour est composé de tours de jeu.
Un tour s'arrête quand tous les joueurs et joueuses ont passé, à leur tour de jeu.

Au début d’un tour, la première personne à jouer doit poser une de ses cartes, face visible, au centre de la table.

Puis chacun peut à son tour de jeu : +
1. Jouer une ou plusieurs de ses cartes ; +
ou +
2. Passer.


=== 1. Jouer une ou plusieurs de ses cartes

La valeur que vous posez doit être strictement supérieure à la valeur au centre de la table.

.Valeur
====
Si au centre il y a un 3, vous devez jouer 4 ou plus.
====

Vous pouvez jouer le même nombre de cartes que le nombre de cartes au centre de la table ou une carte de plus.

.Nombre de cartes
====
Sur une combinaison de 2 cartes, vous pouvez jouer une autre combinaison de 2 cartes ou une combinaison de 3 cartes, mais pas de combinaison de 4 cartes, ni une carte seule.
====

Pour jouer plusieurs cartes, celles-ci doivent obligatoirement être de la même valeur ou de la même couleur.

Quand vous jouez plusieurs cartes, la valeur de ces cartes équivaut au plus grand nombre formé en accolant les chiffres.

.Valeur d'un set
====
Si vous jouez un 2 et un 8 (de la même couleur donc), la valeur de cette combinaison est 82 et non pas 28.

Si vous jouez un 2, un 4 et un 9 (toujours de la même couleur), la valeur est de 942.
====

Après avoir joué une ou plusieurs cartes, vous devez récupérer une des cartes qui se trouvait précédemment au centre de la table.
Cela signifie que :

- S’il y a une seule carte, vous devez la récupérer.
- S’il y en a plusieurs, choisissez celle que vous souhaitez garder et défaussez la ou les autres.


=== 2. Passer

Si vous passez, vous ne posez pas de carte et c’est au tour de jeu du joueur ou de la joueuse à votre gauche.

NOTE: Même si vous passez, vous pourrez jouer à nouveau lors de votre prochain tour de jeu.

Si tout le monde passe à l’exception d’un joueur ou d’une joueuse, le tour se termine, défaussez les cartes restantes au centre de la table.
La dernière personne à avoir posé une carte entame un nouveau tour.
Chacun garde les cartes qu’il a en main.


== Fin d’une manche

Une manche se termine dans deux cas :

1. Si vous êtes la personne qui démarre un nouveau tour et si toutes les cartes que vous avez en main ont la même valeur ou la même couleur.
Vous pouvez les jouer et la manche s’arrête.
Sinon, jouez une seule carte normalement.

2. À n’importe quel moment, si vous jouez une ou plusieurs cartes et si votre main est vide.
Ne prenez pas de carte au centre de la table, la manche s’arrête.

À la fin de chaque manche, vous marquez autant de points que le nombre de cartes qu'il vous reste en main.

Pour commencer une nouvelle manche, distribuez à nouveau 9 cartes à chacun, le joueur ou la joueuse à la gauche du premier joueur de la manche précédente commence un nouveau tour en posant 1 carte.


== Fin de la partie

Pour votre première partie, nous vous conseillons de jouer en 15 points.
Cela signifie que, si un joueur ou une joueuse atteint ou dépasse 15 points, la partie s'arrête et la personne ayant le moins de points gagne la partie.
En cas d'égalité, partagez-vous la victoire.

Par la suite, vous pouvez adapter ce score à ne pas dépasser, en ajoutant 5 points pour des parties plus longues ou en enlevant 5 points pour des parties courtes.
Vous pouvez même jouer en une manche pour des parties très courtes.
