name: Publish presentation to Github Pages

on:
  push:
    branches:
      - main

concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-upload:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build site
        run: ./gradlew App:jsBrowserDistribution
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: App/build/dist/js/productionExecutable
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4